### ISSUE TITLE
easy prop options on right click somehow

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#104]
> mass
> shadow
> color
> gravity toggle
> nocollide
> drawdist (its a unused keyvalue)
> drag and drop
> weld, rope, etc?

**Comment by ghost** [comment]
pls explain and i might attempt. Do you mean by using context menu or just generally right clicking on the prop?

**Comment by ghost** [comment]
@Cynosphere

**Comment by ghost** [comment]
Old issue and it doesn't seem to be going anywhere/not enough info. Reopen if needed.
