### ISSUE TITLE
add room for 18+ content with a separate chat channel

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#107]
> access granted after age verification

I know this was being worked on not that long ago.

**Comment by PotcFdk** [comment]
Note: MetaWorks provides an AgeVerification interface that asks a player to confirm their age with a GUI and all. So if you need the player verification part of the code, I can provide it.

**Comment by KabusDev** [comment]
I can create a 18+ room, it could be added to the lobby or as a televator area, depending on what people would like

**Comment by PotcFdk** [comment]
@KabusIblis what's the status on the map side of things?

**Comment by KabusDev** [comment]
the nightclub I created was intended to be the 18+ room, I'll make it a televator room and re-add it to the map if thats acceptable

**Comment by ajloveslily14** [comment]
There's a system in meta that pops up an "are you 18+" question box maybe that could be used too

**Comment by cdr1996** [comment]
I assume this means adding a physical room to the map, could be nice, I'm not acquainted with mapping for gmod. However the separate chat channel should be possible.

**Comment by cdr1996** [comment]
This isn't going anywhere. Reopen if needed.
