### ISSUE TITLE
chat: paste link -> choose between open/send

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#108]

**Comment by PotcFdk** [comment]
What exactly does this mean? Can somebody explain?

**Comment by Cynosphere** [comment]
Apperently someone forever ago in the old todo thought of an idea of when you paste a link in chat you can choose to open it or send it for some reason.

**Comment by PotcFdk** [comment]
Seems pretty pointless to me. Re-open if you can think of a good reason on why this should be a thing or if what @LUModder said is not what this issue was about.
