### ISSUE TITLE
lua_editor: serverside pastebin with history?

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#109]

**Comment by PotcFdk** [comment]
Idea: Could be realized similarly to the !bug command. A Metastruct GitHub user would create a Gist with the code and add an additional ACL file to allow the original author (and possibly more players as defined by the ACL) to edit/update the Gist.

**Comment by Python1320** [comment]
Still relevant. Could not find good bases. Github gist is basically what we would need.

**Comment by ghost** [comment]
Isn't pythons pastabin thing close as we come to this or is this still relevant?

**Comment by cdr1996** [comment]
@Python1320
