### ISSUE TITLE
Add ban button on SCAP view window

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#113]
send me scap spam now motherfuckers

Bug reported by '<color=255,0,0>Knotcake' (STEAM_0:1:19269760).

**Comment by PotcFdk** [comment]
Shouldn't SCAP just be considered part of the chat / game? In that case, spamming it should be bannable, just like normal chat or prop spam.

**Comment by Cynosphere** [comment]
i agree it's a total waste

(yes lets make it bannable)

**Comment by Cynosphere** [comment]
Added command for it
