### ISSUE TITLE
banned people can send scaps

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#114]
someone got banned for spamming scap and is still sending them even though they are banned

Bug reported by 'snip' (STEAM_0:1:20654783).

**Comment by CassiaPurple** [comment]
Please do something about it I was playing yesterday and was being spammed by the person in question who got banned

**Comment by ghost** [comment]
wasnt there already an issue about this

**Comment by CassiaPurple** [comment]
No but there was one about adding the ability to disable scap altogether

**Comment by Lixquid** [comment]
Duplicate of #78

**Comment by CassiaPurple** [comment]
Oh it was a duplicate oop
