### ISSUE TITLE
coins_drop error

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#116]
[10:19] [Cmd] 'coins_drop' failed for Player [6][Matwey]: lua/coinsys/sv.lua:157: attempt to compare nil with number
stack traceback:
    lua/coinsys/sv.lua:157: in function <lua/coinsys/sv.lua:155>
    [C]: in function 'xpcall'
    lua/includes/modules/concommand.lua:78: in function <lua/includes/modules/concommand.lua:73> (Func @lua/coinsys/sv.lua:155-167) Args='"'0'"'

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by Zeni44** [comment]
Adding `if args[2] == nil then return end` to coins_drop shouldnt be too hard right

**Comment by Cynosphere** [comment]
how would you know if you cant even see the code :v

**Comment by Zeni44** [comment]
"attempt to compare nil with number"
Someone used the command without entering a valid second argument so it errored since it didn't know how much to drop.
Just add a line which checks if the second argument isn't nil, fixed.

**Comment by ghost** [comment]
how do _you_ know it's the second argument, i dont think coins_drop even has a second argument

**Comment by Cynosphere** [comment]
It reads a second argument for no reason even though it shouldn't have one.

**Comment by PotcFdk** [comment]
Apparently fixed by @Python1320 in r11726 / r11882
