### ISSUE TITLE
replace elevator music

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#117]
https://www.youtube.com/watch?v=BtHkC3mSWes

i think this would be better

**Comment by edunad** [comment]
https://www.youtube.com/watch?v=SbIaYZEUF1M

**Comment by Avernakis8** [comment]
https://www.youtube.com/watch?v=8avMLHvLwRQ kek
or this https://www.youtube.com/watch?v=ERahqrn3Ah4 or even this
https://www.youtube.com/watch?v=iMbe6C9dLyI

lal

**Comment by notcake** [comment]
I vote https://www.youtube.com/watch?v=IEz39AxRv6g for elevator music
it's pretty calming and soothing

**Comment by brandsjek** [comment]
Lel no, just put the fucking Daft Punk thing pack, fuck copyright

Or - use Lionel Richie's "Hello, is it me you're looking for?"

Op 7-2-2016 om 20:45 schreef !cake:

**Comment by TW1STaL1CKY** [comment]
What even is it now? Source?
