### ISSUE TITLE
scap_disabled

### ISSUE THREAD

**Issue by KabusDev** [Metastruct/issues#118]
> A SCAP was sent to you but was blocked because you have SCAP disabled.

Should Induce the name of the player who sent it to you, isn't exactly hard to add.

**Comment by Cynosphere** [comment]
cba

**Comment by PotcFdk** [comment]
@LUModder 

> cba

What the fuck. Why do you even bother to comment?

**Comment by Tenrys** [comment]
and disable the notification altogether too

**Comment by ghost** [comment]
Added the name of the player to the notification.
