### ISSUE TITLE
Remove unused hooks on disconnect

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#12]
Remove hooks from devs that are on the server after they disconnected and a certain time has elapsed (just incase of retries)

Bug reported by '<color=33,91,51>Flex' (STEAM_0:0:58178275).

**Comment by PotcFdk** [comment]
I personally don't think that we need this and that it would cause a lot of unnecessary trouble.

**Comment by edunad** [comment]
Lazy Potcfdk :3

**Comment by PotcFdk** [comment]
This isn't about laziness.

**Comment by Python1320** [comment]
hooks don't have an owner. Too much work for too little gain. Slap the devs who leave their annoying hooks on the server when leaving.
