### ISSUE TITLE
coin pot

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#120]
when i spawn the pot it keeps spawned undergound.. but can you guys fix it? 

btw this is the last time i use the reporter i swear.

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Lixquid** [comment]
What the hell is a "coin pot".

**Comment by Cynosphere** [comment]
DarkRP money pot, which was modified for coinsys

**Comment by TW1STaL1CKY** [comment]
Fixed
can't close this thread myself though
