### ISSUE TITLE
multiple urls in one hotlink

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#121]
instantly crashes the game

Bug reported by 'snip' (STEAM_0:1:20654783).

**Comment by Cynosphere** [comment]
why would you even?

**Comment by PotcFdk** [comment]
What do you mean? How do I reproduce this?

**Comment by Cynosphere** [comment]
I attempted to reproduced this:
First go I froze for a second sending it (self pm)
Second go I pasted a lot more and I finally froze beyond return

**Comment by PotcFdk** [comment]
What do you mean? Just sending somthing like http://example.org/examplehttp://example.org/example?

**Comment by Cynosphere** [comment]
Pretty much, but like times that by 100

**Comment by Python1320** [comment]
Can't reproduce when chatsounds is disabled.

**Comment by Cynosphere** [comment]
I'm assuming it had to do with the underline links had before the fonts update
