### ISSUE TITLE
QBox bugs

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#123]
[10:11] Player [22][Ducky Canard] ERR: gamemodes/sandbox/entities/effects/selection_ring.lua:12: Tried to use a NULL entity!
1. SetCollisionBounds - [C]:-1
   1. unknown - gamemodes/sandbox/entities/effects/selection_ring.lua:12
   2. Effect - [C]:-1
      1. unknown - gamemodes/sandbox_modded/entities/effects/selection_indicator2/init.lua:18

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by Cynosphere** [comment]
Players that got this error crashed soon after.

**Comment by Cynosphere** [comment]
Okay it happens when CBaseEntityList::AddNonNetworkableEntity: no free slots!
