### ISSUE TITLE
remove ability to sh webaudio

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#126]
its getting annoying trying to listen to my music stream visualizer and people are sh-ing chatsounds near me

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by notcake** [comment]
https://blogs.msdn.microsoft.com/oldnewthing/20110310-00/?p=11253

**Comment by PotcFdk** [comment]
What cake said is true for most things that happen in Garry's Mod.
You're either going to have to get a solution implemented in Garry's Mod or just join the war.

**Comment by danielga** [comment]
My temporary solution when people were being cunts was to make 'sh' work only on the issuer. I think it's a good compromise because, the way it is right now, it's a very intrusive command.

**Comment by Lixquid** [comment]
I think the main opposition to that is that irritating sounds then need to
be sh'd by everyone, leading to a colossal flood of sh whenever something
happened.

Basically there's no real systemic solution to this so the best course of
action is to administrate bad players.

**Comment by ghost** [comment]
i have a _hacky_ way to make streams not do this: by checking if they are paused and if they are then just resume them

if you might ask how to intentionally pause them, youve got to make it not resume if a variable is not set, then just unset that variable once you want to resume it
