### ISSUE TITLE
Chat Bubble shows private Messages

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#127]
Players can see private Messages like /pm and so on in the Chatbubble.

Bug reported by '<color=255,120,0>Google' (STEAM_0:1:66459838).

**Comment by ghost** [comment]
u wot m8
what about /pm??? that isnt even a command???

**Comment by ghost** [comment]
Close please. (It looked as if there is a /pm Command because someone used it and no Chat Message popped up)

**Comment by Cynosphere** [comment]
pm is overwritten by GCompute anyways.

**Comment by Tenrys** [comment]
no, pm as a command doesn't exist. pm2 does, because cake thought about the actual private messaging command that could exist by the name pm, but it doesn't.

**Comment by Cynosphere** [comment]
It does exist as an alias for pm2 afaik as long as there's NOT a pm command

**Comment by ghost** [comment]
no it doesnt

**Comment by Cynosphere** [comment]
Worked for me when I tested it so
