### ISSUE TITLE
Chatsounds Pre-proccessor errors

### ISSUE THREAD

**Issue by Mikeai** [Metastruct/issues#128]
Not sure if anyone else is getting this issue, but when running the pre-proccessor for chatsounds, it yells at me about non-lowercase paths in Lixquid's chatsounds folder, if there is a fix to this I yet know, do inform me of it

**Comment by Cynosphere** [comment]
One of @TrenchFroast's commit's removed all the lowercase chatsounds for Lix :v

**Comment by Cynosphere** [comment]
also this is the wrong issues to be posting this

**Comment by ghost** [comment]
@LUModder because git went retardation mode for me, not my fault
thank based microsoft for very good file handling
