### ISSUE TITLE
lua/metastruct/items/gui/inventory.lua:174: attempt to index local 'item' (a nil value)

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#130]
When I open my Inventory on Server 2 that happens:

[Cmd] 'items_toggle_inventory' failed for Player [1][Google]: lua/metastruct/items/gui/inventory.lua:174: attempt to index local 'item' (a nil value)
stack traceback:
    lua/metastruct/items/gui/inventory.lua:174: in function 'UpdateInventory'
    lua/metastruct/items/gui/inventory.lua:233: in function 'UpdateInventory'
    lua/metastruct/items/gui/inventory.lua:259: in function <lua/metastruct/items/gui/inventory.lua:249>
    [C]: in function 'xpcall'
    lua/includes/modules/concommand.lua:78: in function <lua/include

**Comment by PotcFdk** [comment]
I don't get it:

```
171         local item = self.msitems[class] or vgui.Create("msitems.ItemPanel", self)
172         local text = msitems.GetInventoryInfo(class)
173                         
174         item:SetCount(table.count)
```

**Comment by Python1320** [comment]
does this still happen?

**Comment by ghost** [comment]
No.
