### ISSUE TITLE
MSReporter seems to be broken?

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#131]
lua/autorun/server/msreporter.lua:36: attempt to index local 'resp' (a nil value)
1. unknown - lua/autorun/server/msreporter.lua:36

Error happened when I tried to submit #130

**Comment by PotcFdk** [comment]
Seems to have been a temporary API error.
I improved the error handling, so that you get a friendly-ish warning.

**Comment by PotcFdk** [comment]
I noticed that the web relay was broken, too.
The !bug command should be working again. Sorry about that.
