### ISSUE TITLE
SCAP Friends only

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#132]
What about an option to allow scaps only from friends?

**Comment by LUModder** [comment]
Dibs

**Comment by Techbot121** [comment]
I didn't touch the SCAP code yet, but this should be fairly easy to implement.

**Comment by Cynosphere** [comment]
Considering I already implemented blocking this won't be hard

**Comment by Tenrys** [comment]
Is this done @LUModder ?

**Comment by Cynosphere** [comment]
Forgot about it :v

**Comment by Myaats** [comment]
3 lines of code later and this has been added :bullettrain_front:
