### ISSUE TITLE
Propeller engine and jetpack disappear after equipping

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#134]
Mar 23 10:19:01 <ShadowBlood>  bug: propeller engine and jetpack dissapear after equipping, will stay on for a couple seconds before dissapearing from the user's inventory

25.03.16 [03:01:31] <ShadowBlood> (UPDATE) bug: the glitch with propeller engine & jetpack also happens with the coin detector and coin magnet

**Comment by Cynosphere** [comment]
reopen if still valid
