### ISSUE TITLE
global sed memory overflows

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#14]
When using sed with the global modifier, recursive patterns can cause extremely long frames and out of memory errors.

Bug reported by 'Lixquid' (STEAM_0:1:22847820).

**Comment by PotcFdk** [comment]
@Lixquid how can I reproduce it?

**Comment by Cynosphere** [comment]
s/./anything/g
This reproduces it.

**Comment by PotcFdk** [comment]
I think I will just roll back to an older version. I initially wanted more control for stuff like case insensitivity, but instead it broke patterns and some other things.
