### ISSUE TITLE
e2 breaking

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#140]
e2 starts breaking down and stops working on the server after a while reason unknown and holos straight up stop working

Bug reported by '<color=87,6,121>KaosHeaven ' (STEAM_0:0:69785433).

**Comment by Cynosphere** [comment]
Pretty sure MetaMan's reasoning of "desyncing" or something with CurTime after the server has been up for so long without restarting might be causing this

**Comment by CassiaPurple** [comment]
possibly
it would be helpful if we could get some sort of fix (another note it only happens on meta)

**Comment by notcake** [comment]
We have notified our DevOps team and have dispatched a team of ninjaneers to investigate the problem.

**Comment by CassiaPurple** [comment]
@notcake lol thanks again cake

**Comment by edunad** [comment]
Break my e2, ill break your legs :+1:

**Comment by danielga** [comment]
break my legs, i'll break your face :+1:

**Comment by CassiaPurple** [comment]
Break my face, I'll break your dick :+1:

**Comment by ghost** [comment]
@Kaosheaven what if said person doesn't have a dick :^)

**Comment by CassiaPurple** [comment]
then fingers idk

**Comment by Cynosphere** [comment]
:+1: :^)

**Comment by Python1320** [comment]
Give example E2 that breaks so we can test after a day of uptime

**Comment by CassiaPurple** [comment]
Sure thing but idk if you'll be around when I get home (currently using forkhub on my phone so I don't really have anything on me)

**Comment by Python1320** [comment]
holos are fixed. DO tell if there's something else.

**Comment by ghost** [comment]
yus. der is something else.
When lights from lightCreate() are parented and then the parented to object is destroyed the light counter does not decrease so it thinks I'm at max lights but really I have no lights spawned, it might be the same as the holos not spawning glitch.
Also, it should verify if the light is real else it will try to use a null entity sometimes.
for(I = 1,50){
holoCreate(I,entity():pos()+vec(0,0,100))
lightCreate(I,holoEntity(I):pos())
lightParent(I,holoEntity(I))
holoDelete(I)}
Light stops working if spawned more than 3 times I'm guessing.
