### ISSUE TITLE
Map hole in doorway near edge of build

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#143]
we need to fix this
![](http://i.imgur.com/79qcHFb.jpg)

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by notcake** [comment]
SWAT teams and sniffer dogs have been deployed to deal with the situation.

**Comment by Lixquid** [comment]
And it would have been a nice bug report if not for the unnecessary second
line

**Comment by Cynosphere** [comment]
Assuming this has been fixed in either 164 or 175
