### ISSUE TITLE
rp bug 

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#147]
http://i.imgur.com/qOAwgHh.jpg >safezone. i still get the 10 secs spawn protection...

and we still spawn into a place outside of the rp area... http://i.imgur.com/naMosJT.jpg

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Cynosphere** [comment]
Yes, the safezone resets your spawn protection when you enter and kills the timer, so you won't get the message saying that spawn protection was removed. I was going to move the spawns into the safezone anyways but haven't gotten to it
