### ISSUE TITLE
Remove rp autoheal from banned players

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#148]
forgot to tell the banned players get autohealed fast... how about remove them so we can keel em faster?

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by PotcFdk** [comment]
I don't see the point.

**Comment by Cynosphere** [comment]
People like to farm banned people for coins in RP and with the new autoheal system it kinda breaks it a bit.

**Comment by Cynosphere** [comment]
I'm assuming no one is going to do this
