### ISSUE TITLE
Hours aren't counted cross-server

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#149]
ex: person who has 25 hours that was on #2 all the time doesnt have the hours #1

I honestly think this is both good and bad cause it means people that idle for hours on #2 dont have it on #1 but it's also a pain that it doesnt transfer

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by PotcFdk** [comment]
I thought it was synced in some way? @Python1320?

**Comment by Cynosphere** [comment]
It's only scoreboard synced, but not fully

**Comment by ghost** [comment]
It is synced while meta2 is online but only on the scoreboard.

**Comment by Python1320** [comment]
should have been fixed long ago
