### ISSUE TITLE
Area Control still works if entity is removed with context menu

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#15]
As title says.

Bug reported by '<color=150,100,150>Flex' (STEAM_0:0:58178275).

**Comment by Python1320** [comment]
can you verify this? could be there was a secondary area control

**Comment by Cynosphere** [comment]
Dunno if it bug has been recreated

**Comment by SpiralP** [comment]
tested 'Remove contraption' and 'Remove' from context menu, stops disallowing things once removed like it should
