### ISSUE TITLE
Deal or No Deal

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#150]
lua/entities/mitt_dond_screen.lua:643: attempt to index a nil value
1. GetPlayCount - lua/entities/mitt_dond_screen.lua:643
   1. StartGame - lua/entities/mitt_dond_screen.lua:743
   2. StartGame - lua/entities/mitt_dond_entry.lua:126
      1. unknown - lua/entities/mitt_dond_entry.lua:178

**Comment by Cynosphere** [comment]
More info:
- Allows playing more than once due to a missing function
- Spams chat when AFK timer runs down
