### ISSUE TITLE
Fix the crane's magnet removal server crash

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#153]
i wish you guys could remove the crane.. bec if the magnet's gone the server'll die.. btw who want to use that tho? .-.

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Vuthakral** [comment]
I use it :disappointed: :dragon_face: 

(I wouldn't really care if it were removed though)

**Comment by Tenrys** [comment]
think about better issue titles in the future please

**Comment by Python1320** [comment]
fixed
