### ISSUE TITLE
metastruct.org domain is dead

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#154]
We either need to
1. renew it
2. move everything over to metastruct.net

![](https://my.mixtape.moe/bmxcfj.png)

**Comment by Cynosphere** [comment]
So no one's gonna do anything about it and just let the server not be updated at all?

**Comment by PotcFdk** [comment]
What is missing?

**Comment by Cynosphere** [comment]
- SSO
- Rocket/GServ
- SVN repos
- MSDNAA (or whatever it is)
- Webchat

**Comment by PotcFdk** [comment]
SVN repos don't have anything to do with this.

**Comment by Cynosphere** [comment]
But they do because they're linked to `svn.metastruct.org`

**Comment by PotcFdk** [comment]
Then relocate them to `svn.metastruct.net`
For everything else, @Python1320 shall be used

**Comment by Cynosphere** [comment]
Python said he said he CBA to set up everything and gave us a temp rehash solution

**Comment by PotcFdk** [comment]
This issue isn't fixed according to your list of issues.

**Comment by Tenrys** [comment]
I would really want this fixed, I can't "qu rehash" server 1 myself due to some dumb issue with my ISP.
