### ISSUE TITLE
Title's broken

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#155]
i can't set my title.. when im using the console cmd it gives meh this error

[Titles] Adding title (delay: 4.0s): gone to paris in 8 days
[Titles] Sending... [Cmd] 'titles_add' failed for Player [25][^7Bjoern90 (DEN)]: lua/autorun/pl_title.lua:129: attempt to get length of upvalue 'tdat' (a boolean value)
stack traceback:
    lua/autorun/pl_title.lua:129: in function '_Transmit'
    lua/autorun/pl_title.lua:138: in function 'SetTitles'
    lua/autorun/pl_title.lua:188: in function <lua/autorun/pl_title.lua:173>
    [C]: in function 'xpcall'
    lua/includes/modules/concommand.lua:94: in function <lua/includes/modules/concommand.lua:71> (Func @lua/autorun/pl_title.lua:173-191)

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Cynosphere** [comment]
@Python1320 ping
