### ISSUE TITLE
AFK Lock unsits you

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#156]
i always sitting while watching videos but after i go afk in 2:30 mins i stand up for no reason.. maybe it's a bug?

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Cynosphere** [comment]
So I guess we need to not have locking if sitting

**Comment by Python1320** [comment]
disabled afk locking. too many drawbacks.
