### ISSUE TITLE
[DOND] AFK kicked players can play again

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#159]
I dunno if something was changed or if it applies to everyone too no matter if you've played or not

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by mitterdoo** [comment]
the game allows a player two do-overs in case something goes wrong (server crash/player disconnect/afk) before the money they're walking away with is revealed (accepted offer/end of game). if the game is allowing more than 3 games to a player, please post a comment and i will look into it.

**Comment by Lixquid** [comment]
Looks like Working As Intended.

Reopen if confirmed bug.
