### ISSUE TITLE
Steam emoticons break chathud messages

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#16]
This might apply to many things, but take this as an example:
`Last seen today at 00:52. (01:07:14 ago)`
The :07: is not rendered in the chat.

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by LUModder** [comment]
:07: seems to be the only broken one

**Comment by Python1320** [comment]
there's no current way to signal which part of messages should have emoticons parsed. Originally I had single or double number emoticons banned for this specific reason.

**Comment by PotcFdk** [comment]
Maybe they should be rebanned.

**Comment by Tenrys** [comment]
That seems like a stupid way to handle the problem.

**Comment by Tenrys** [comment]
I think I've got a solution.

**Comment by Tenrys** [comment]
Fixed.
