### ISSUE TITLE
crane bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#161]
http://i.imgur.com/i1hD3ja.jpg

[Hook] Think -> "MSAvehiclecontrol" failed: lua/autorun/client/msavehicles_init_entity.lua:22: attempt to call method 'IsMSAVehicle' (a nil value)
stack traceback:
    lua/autorun/client/msavehicles_init_entity.lua:22: in function 'MSAvehcontrol'
    lua/autorun/client/msavehicles_init_entity.lua:173: in function 'func'
    lua/includes/modules/hook.lua:96: in function <lua/includes/modules/hook.lua:87>
    [C]: in function 'xpcall'
    lua/includes/modules/hook.lua:129: in function <lua/includes/modules/hook.lua:111>

i can't move the crane.. gg

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Tenrys** [comment]
what the fuck did you do.

**Comment by Techbot121** [comment]
This happens because the Crane doesn't have the Vehicle metatable functions, which the MSAvehiclecontrol looks up I think.

**Comment by Techbot121** [comment]
The MSAvehicle stuff used to be on BitBucket but now I have no idea where they are. @PotcFdk ??

**Comment by PotcFdk** [comment]
Weird, I thought this was fixed. I'll check this out.

**Comment by PotcFdk** [comment]
Fixed.

**Comment by Cynosphere** [comment]
I swear this was a duplicate bug...

Yeah #157

**Comment by PotcFdk** [comment]
Seems like in #157 I fixed a related serverside issue. This time, we should be okay, though.

**Comment by Cynosphere** [comment]
Was antipenetration of the magnet fixed so it doesn't get frozen?

**Comment by PotcFdk** [comment]
That's not in the scope of this issue.
