### ISSUE TITLE
elevators

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#164]
THE FUCKING ELEVATORS KEEPS SENDING US TO HELL OR NEXT TO MSA FUCKING FUCK!!!!!!!!!

yeh i mad atm. and the devs are lazy as fuck.

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by danielga** [comment]
I'm mad about the fact that you think you're entitled to our free time!!!

**Comment by notcake** [comment]
bro do u even lift

**Comment by danielga** [comment]
bro do u even meme

**Comment by Lixquid** [comment]
Can we ban baby bjoern from bug reporter yet

**Comment by notcake** [comment]
fite me irl lixquid

**Comment by danielga** [comment]
you're not getting rid of me that easily

**Comment by Cynosphere** [comment]
unproductive issue, no steps for recreation

reopen if it's a serious bug
