### ISSUE TITLE
name changer bug?

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#165]
when ever a user changes the name i see a double message about it http://i.imgur.com/Lp33Sed.jpg

but in irc you can see it triple message .-.

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Techbot121** [comment]
I just looked it up, there are two functions that use two separate hooks `player_info_changed` and `NameChange` both call `chat.AddText`.

Now the question is which one to get rid of.

**Comment by Zeni44** [comment]
I also noticed it printing 3 times in IRC. Is that intended?
Or was that a bug on my end

**Comment by PotcFdk** [comment]
IRC seems to be unaffected, not sure what @ToastyEngineer is talking about.

**Comment by ghost** [comment]
@PotcFdk sometimes (sometimes) it displays 3 equal nick change messages in a row

**Comment by PotcFdk** [comment]
Is this still happening? I haven't been observing this further.

**Comment by Cynosphere** [comment]
There just doesn't seem to be a way to detect it because the chatprinted name change is a steam name change but it never shows with the nickname change if the player has a nickname already

**Comment by PotcFdk** [comment]
This is probably not happening anymore. Re-open if it does.
