### ISSUE TITLE
miku

### ISSUE THREAD

**Issue by SpiralP** [Metastruct/issues#166]
oy @PotcFdk can we remove your precious mikus addons now that we have outfitter?

**Comment by Techbot121** [comment]
![](http://techbot.xyz/ShareX/screenshots/2016/05/24/miku_%C2%B7_Issue_%23166_%C2%B7_Metastructissues_-_Google_Chr_13-22_1047.png)
![](http://techbot.xyz/ShareX/screenshots/2016/05/24/13-25_1049.png)

**Comment by danielga** [comment]
😂

**Comment by Cynosphere** [comment]
I don't get why we should be forced to have these on here honestly. Just slows down download times and adds unneeded trash (litterally) to our games. Please just let Outfitter take this over

**Comment by SpiralP** [comment]
I've recently seen a few people using the ragdoll forms of the miku so I guess it's not entirely useless

**Comment by Cynosphere** [comment]
@SpiralP Yeah but it's only for sexposes and for "le funny scaps" of them

**Comment by Techbot121** [comment]
imo the only useful thing on that might be the hair bones.

**Comment by Cynosphere** [comment]
vote was made to remove custom player models in favor for outfitter, why isn't this done yet?

**Comment by SpiralP** [comment]
:cat: :cat2: :joy_cat:

**Comment by PotcFdk** [comment]
I've been doing some outfitter testing and I guess it's okay these days.
