### ISSUE TITLE
Improve the god mode experience

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#17]
As seen [here](http://steamcommunity.com/groups/metastruct/discussions/0/483366528902405708/)

**Comment by Python1320** [comment]
task 1: Send to hell buyable item
task 2: damage reflection or similar

**Comment by TW1STaL1CKY** [comment]
I know this is a bit late, but I started working on something to do with this.
Not much at this time

**Comment by Python1320** [comment]
Coded send to hell
