### ISSUE TITLE
gun in lobby

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#171]
somehow we can't use the guns from the gun room in lobby .-. idk who killed it.

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by aminpeck** [comment]
Python1320 did that on purpose bud.

**Comment by Cynosphere** [comment]
It would be nice if Python added checks for restrictions at the most, party mode I don't care much about.

**Comment by Tenrys** [comment]
Closed, I suppose that's not an issue, except if that's the case even in party mode
