### ISSUE TITLE
coin loss bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#173]
when ppl joins the server they can lost all the coins by simply collect 1 coin with 1 in vaule and they'll lost all the dosh .-. i feel sorry for qidikun bec i did it to him .-. sorry pal if you're reading this...

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Lixquid** [comment]
Upside down bjoern strikes again .-.

**Comment by Lixquid** [comment]
Also would it kill you to use some semblance of the English language in bug reports, we need to know what the steps are to reproduce the problem and affected areas, not who you "feel sorry for bec you did it to them".

**Comment by Tenrys** [comment]
Should be fixed by now, please tell if not.

**Comment by Tenrys** [comment]
I'm not sure Bjoern even knows where the hell his bug reports go, or if he has an account here, so it's probably better to tell him that directly instead of here.

**Comment by ghost** [comment]
there appears to be a bjoern90 github account but i'm not quite sure if it's him
