### ISSUE TITLE
Some VGUI text elements render black text when they shouldn't

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#174]
This happens in a lot of places, for example when you type !tasks, go to any achievement. You will notice that the description is black/dark, even though it should be white-ish.

The relevant code line is:

`ADesc:SetTextColor(Color(240,240,240,255))`

The code didn't change, but apparently something else must have changed the behavior.
Adding a `print(ADesc.SetTextColor, ADesc:GetTextColor())` directly after the line above yields: `Func:(util.lua: 171) 20 20 20 255` (!?)

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by PotcFdk** [comment]
@Python1320 maybe?

**Comment by Tenrys** [comment]
Fixed, it was an issue in Metastruct's skin.
