### ISSUE TITLE
RP Flag

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#176]
It would be nice to know if a person is in RP by looking at the scoreboard.
I teleported to a guy I thought was making lag and scared him because he was in RP. XD
It could look like this or worse I don't care.
http://i.imgur.com/DS4mhhy.png huehuehue.

**Comment by notcake** [comment]
I vote for a weed icon

**Comment by knoxed** [comment]
I thought you couldnt teleport to people in RP unless you were in RP too?

**Comment by ghost** [comment]
No you can't teleport to anyone in RP.

**Comment by TW1STaL1CKY** [comment]
Done, "In RP" on the scoreboard is represented by a gun icon now.

(I can't close issues help)
