### ISSUE TITLE
!goto doesn't work for nicknames that use markup

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#18]
For those people that use multiple <color> (me) and ^ tags

Bug reported by '<color=0,255,0>F<color=0,255,64>l<color=0,255,128>e<color=0,255,196>x' (STEAM_0:0:58178275).

**Comment by Tenrys** [comment]
I don't even get what you mean

**Comment by LUModder** [comment]
People who use multiple markup tags for each letter are unable to be gone to

**Comment by Tenrys** [comment]
i'll do it later

---- Flex wrote ----

People who use multiple markup tags for each letter are unable to be gone to

---

**Comment by SpiralP** [comment]
fixed in https://github.com/Metastruct/luadev/commit/bf2f85ed0293e0c2890199d49e7de4f10c9b98d0
