### ISSUE TITLE
TP to some one in rp zone

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#180]
I know how to tp to someone in an RP soon if you're in a building area. it's easy all you have to do is kill yourslef stay dead and double click a player on a tap the tab menu and then you're there. thanks -blueangel512

Bug reported by '[NN] blueangel512' (STEAM_0:1:116947843).

**Comment by Cynosphere** [comment]
also can be done for reviving in rp where you just go somewhere, die and then do .back

**Comment by Cynosphere** [comment]
assuming this was fixed already

reopen if I'm wrong
