### ISSUE TITLE
Tv gui

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#181]
if you are lissoning to tv then type vgui_cleanup 1 then the song brakes and screan go even if its not your tv.

Bug reported by '[NN] blueangel512' (STEAM_0:1:116947843).

**Comment by Techbot121** [comment]
Translation:

If you're using PlayX and then use vgui_cleanup 1 the current video stops even if it's not your own.

Seems like a clientside "issue" not sure if playx_enabled 0 then back to 1 fixes it but maybe have a command like !fixplayer to reload playx players you're subscribed to.

**Comment by Cynosphere** [comment]
Will try to add playx and mediaplayer to the blacklist for vgui_cleanup

**Comment by ghost** [comment]
Blacklisted it.

**Comment by Tenrys** [comment]
also add socketdev panel?

**Comment by Cynosphere** [comment]
yes please add socketdev

**Comment by ghost** [comment]
why does it use a panel and not a think hook

**Comment by ghost** [comment]
Done.
