### ISSUE TITLE
Outfitter: Console spam when "Only load outfits from friends" is enabled

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#182]
http://i.imgur.com/GeS0T4t.jpg

If a non-friend is using an outfit and you have "Only load outfits from friends" enabled, it prints the lines shown in the image every second per player in range.

Bug reported by 'TW1STaL1CKY' (STEAM_0:0:33106902).

**Comment by Cynosphere** [comment]
looks like left over debug printing

**Comment by Techbot121** [comment]
there is actually a convar for it 
`outfitter_dbg 0/1`

**Comment by Noiwex** [comment]
Why does this setting even exist to begin with.
