### ISSUE TITLE
Picker2 or Drones glitch, Drones drone on after being deleted and leave little flexes behind

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#183]
I had picker2 on and noticed a drone shape cluster of flexes. I spawned like 100 drones and removed them and they weren't even being recycled.
http://i.imgur.com/WGjFvYJ.jpg
The problem up close: http://i.imgur.com/DQNXQY2.jpg

Average FPS for all clients didn't seem to change though[.](url)

**Comment by Cynosphere** [comment]
not even a bug, just a "joke" directed at me
