### ISSUE TITLE
bag dance

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#184]
If you type !dance then when your danceing you press C then you screan goes all fucked up xD

Bug reported by '<color=10,10,250>BlueAngel512' (STEAM_0:1:116947843).

**Comment by Cynosphere** [comment]
issue reporting level: bjoern

honestly these reports are as useless

**Comment by PotcFdk** [comment]
I'm sure most Garry's Mod players know what this is about, @LUModder.
If you don't, just try it out.

(Note: I don't know whether this should/needs to be worked on, but that's what should be decided, not "herp derp useless".)

**Comment by Cynosphere** [comment]
But it's not a bug, it's a feature of either CTP or something else.

**Comment by ghost** [comment]
you misunderstood the bug report, if you have the context menu open while dancing the screen spazzes out

**Comment by Myaats** [comment]
fixed after next server restart
