### ISSUE TITLE
Too many RT cameras

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#187]
RT cameras can be can spammed past the prop limit.
http://i.imgur.com/GGLwZ4Q.jpg - 314 cameras. eek.
Also spams EPOE.

**Comment by Cynosphere** [comment]
How do you know it spams EPOE? Care to explain that too?

**Comment by ghost** [comment]
When you create an RT camera the spooky ppl with epoe know.

**Comment by Cynosphere** [comment]
Doesn't matter, I want to know how you have EPOE access

**Comment by ghost** [comment]
**he doesn't**
people with epoe access him told him to stop spamming it

**Comment by TW1STaL1CKY** [comment]
The only reason it was spamming EPOE was because he was using a script to do it.

**Comment by ghost** [comment]
You need to stop assuming things flex lol

**Comment by Myaats** [comment]
should have been fixed with Metastruct/wire-extras@f64b09899df32ba9151babb6b9ceaf615ad1522c
