### ISSUE TITLE
Possible aowl / prop protection bugs

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#19]
Giggle: should i reset the server if aowl is half-responsive
Giggle: prop ownership is acting up
Giggle: and certain 'aowl' commands arent working
Giggle: noticed things were fucked up when random players could grab other people's shit
Giggle: regardless of friend settings
Giggle: or being a dev

No idea what this is about, but it doesn't seem right and somebody should maybe investigate.

**Comment by LUModder** [comment]
Something weird has to be killing CPPI/aowl if this happens, yeah, restart will fix it, but why is it happening is the real question.

**Comment by Python1320** [comment]
If it starts becoming a problem I'll re-enable error logging.

**Comment by Cynosphere** [comment]
Has this been able to be recreated or happen again since?

**Comment by Cynosphere** [comment]
Verbal just had this happen again with prop protection so, it has been recreated but not 100% knowing what causes it.

**Comment by PotcFdk** [comment]
Still relevant? It's been a while.

**Comment by Cynosphere** [comment]
Hasn't happened since last month so, I doubt it.

**Comment by PotcFdk** [comment]
Reopen if it happens again.
