### ISSUE TITLE
KeyPress "autosit" hook fails when using the chair next to the vending machine

### ISSUE THREAD

**Issue by TW1STaL1CKY** [Metastruct/issues#191]
I don't know what's happening in this file's line, so I'd rather not touch it myself  :s

![Image](http://i.imgur.com/IZqquSV.jpg)

On gm_construct_m_217, using the wooden chair next to the vending machine produces an error on both server and client:

```
[Hook] KeyPress -> "autosit" failed: lua/includes/modules/bsp.lua:144: name not found for: 2048
stack traceback:
    [C]: in function 'assert'
    lua/includes/modules/bsp.lua:144: in function 'GetStaticProps'
    lua/autorun/sit_staticprop.lua:103: in function 'need_sitdata'
    lua/autorun/sit_staticprop.lua:208: in function 'func'
    lua/includes/modules/hook.lua:109: in function <lua/includes/modules/hook.lua:100>
    [C]: in function 'xpcall'
    lua/includes/modules/hook.lua:143: in function <lua/includes/modules/hook.l
Player [37][TW1STaL1CKY] ERR: [Hook] KeyPress -> "autosit" failed: lua/includes/modules/bsp.lua:144: name not found for: 2048
stack traceback:
    [C]: in function 'assert'
    lua/includes/modules/bsp.lua:144: in function 'GetStaticProps'
    lua/autorun/sit_staticprop.lua:103: in function 'need_sitdata'
    lua/autorun/sit_staticprop.lua:208: in function 'func'
    lua/includes/modules/hook.lua:109: in function <lua/includes/modules/hook.lua:100>
    [C]: in function 'xpcall'
    lua/includes/modules/hook.lua:143: in function <lua/includes/modules/hook.l
```

**Comment by Techbot121** [comment]
doesn't seem to happen anymore

**Comment by Chiron31** [comment]
hey, we happened to have this map and we cant find any information about it. What happened to this map? Do you know anything about this map?

**Comment by Chiron31** [comment]
> doesn't seem to happen anymore
hey, we happened to have this map and we cant find any information about it. What happened to this map? Do you know anything about this map?

**Comment by Chiron31** [comment]
> I don't know what's happening in this file's line, so I'd rather not touch it myself :s
> 
> ![Image](https://camo.githubusercontent.com/6ced1437276cd0decb5e0fe0e91da2a0eb0b59e86cb4bb0756f05b8f069a9ae7/687474703a2f2f692e696d6775722e636f6d2f495a71717553562e6a7067)
> 
> On gm_construct_m_217, using the wooden chair next to the vending machine produces an error on both server and client:
> 
> ```
> [Hook] KeyPress -> "autosit" failed: lua/includes/modules/bsp.lua:144: name not found for: 2048
> stack traceback:
>     [C]: in function 'assert'
>     lua/includes/modules/bsp.lua:144: in function 'GetStaticProps'
>     lua/autorun/sit_staticprop.lua:103: in function 'need_sitdata'
>     lua/autorun/sit_staticprop.lua:208: in function 'func'
>     lua/includes/modules/hook.lua:109: in function <lua/includes/modules/hook.lua:100>
>     [C]: in function 'xpcall'
>     lua/includes/modules/hook.lua:143: in function <lua/includes/modules/hook.l
> Player [37][TW1STaL1CKY] ERR: [Hook] KeyPress -> "autosit" failed: lua/includes/modules/bsp.lua:144: name not found for: 2048
> stack traceback:
>     [C]: in function 'assert'
>     lua/includes/modules/bsp.lua:144: in function 'GetStaticProps'
>     lua/autorun/sit_staticprop.lua:103: in function 'need_sitdata'
>     lua/autorun/sit_staticprop.lua:208: in function 'func'
>     lua/includes/modules/hook.lua:109: in function <lua/includes/modules/hook.lua:100>
>     [C]: in function 'xpcall'
>     lua/includes/modules/hook.lua:143: in function <lua/includes/modules/hook.l
> ```

hey, we happened to have this map and we cant find any information about it. What happened to this map? Do you know anything about this map?
