### ISSUE TITLE
Player kill display.

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#193]
If people with the same nick kill each other it shows as a suicide, also killing multiple people with the same name only shows deaths for the first person with that name.

Bug reported by '<color=0,191,255>Not Mike' (STEAM_0:1:80004288).

**Comment by Python1320** [comment]
Normal Garry's Mod should have this problem too, see https://github.com/Facepunch/garrysmod/blob/784cd57576d85712fa13a7cea3a9523b4df966b0/garrysmod/gamemodes/base/gamemode/cl_deathnotice.lua#L142
