### ISSUE TITLE
Failed to load sound "chatsounds\autoadd\..."

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#195]
Somebody decided that it'd be a good idea to hardcode chatsounds filepaths in srvaddons code. This leads to errors such as this one:

`Failed to load sound "chatsounds\autoadd\lixquid\squiddistress\fescape2.ogg", file probably missing from disk/repository`  

At least the following file is causing this type of errors: `srvaddons\KeyCode\lua\codes\woomy.lua`.

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by TW1STaL1CKY** [comment]
@Lixquid wants his squids

**Comment by Lixquid** [comment]
TODO: fix

**Comment by Myaats** [comment]
That keycode file seems to have been removed, and there are no other mentions of the sound file anywhere in the repo. Closing
