### ISSUE TITLE
Outfitter cache loading failed

### ISSUE THREAD

**Issue by EccentricManuals** [Metastruct/issues#198]
Sorry if this isn't the right place to put this but I encountered a strange bug with outfitter. I was loading a playermodel with it when my game crashed. When I attempted to re-load it, I was met with a script error along with the console reporting that the cache file had failed to load. Here's some screenshots:
<a href="http://imgur.com/MYmHkcA"><img src="http://i.imgur.com/MYmHkcA.jpg?1" title="source: imgur.com" /></a>
<a href="http://imgur.com/qHaZHK2"><img src="http://i.imgur.com/qHaZHK2.jpg?1" title="source: imgur.com" /></a>
As you can see, console is reporting errors and the submit button has been greyed out (likely because it couldn't read the model in the first place). I've tried everything but I can only assume that the cache has been corrupted since I crashed while loading it. If there is already a fix for this, please let me know.

Here's the workshop model I used: http://steamcommunity.com/sharedfiles/filedetails/?id=780957556

**Comment by ajloveslily14** [comment]
cannot reproduce, assuming fixed
