### ISSUE TITLE
PAC indicator always spinning when no awesomium

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#20]
it's always there and it bugs me

Bug reported by '<color=255,255,255>Napstablook' (STEAM_0:0:58178275).

**Comment by notcake** [comment]
It's your own damn fault for fucking with awesomium.

**Comment by meepdarknessmeep** [comment]
im gay :-1:

**Comment by Python1320** [comment]
Disable pac ogg (and/or webaudio, not sure which one) and urltex modifiers using their cvars (pac_enable_urltex or something) so they won't try loading.
