### ISSUE TITLE
Lua Screen Error: rnd3.lua: recursecomments (rnd3.lua:26: attempt to index a nil value)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#200]
[ERROR] lua/lua_screens/screens/rnd3.lua:26: attempt to index a nil value
  1. recursecomments - lua/lua_screens/screens/rnd3.lua:26
   2. recursecomments - lua/lua_screens/screens/rnd3.lua:48
    3. recursecomments - lua/lua_screens/screens/rnd3.lua:48
     4. recursecomments - lua/lua_screens/screens/rnd3.lua:48
      5. recursecomments - lua/lua_screens/screens/rnd3.lua:48
       6. recursecomments - lua/lua_screens/screens/rnd3.lua:48
        7. recursecomments - lua/lua_screens/screens/rnd3.lua:48
         8. recursecomments - lua/lua_screens/screens/rnd3.lua:48
          9. recursecomments - lua/lua_screens/screens/rnd3.lua:48
           10. recursecomments - lua/lua_screens/screens/rnd3.lua:48
            11. recursecomments - lua/lua_screens/screens/rnd3.lua:48
             12. recursecomments - lua/lua_screens/screens/rnd3.lua:48
              13. recursecomments - lua/lua_screens/screens/rnd3.lua:48
               14. recursecomments - lua/lua_screens/screens/rnd3.lua:48
                15. recurse

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by PotcFdk** [comment]
Should be fixed. Re-open if it isn't.
