### ISSUE TITLE
Lua Screen - Steam Group Comments

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#201]
Sometimes it doesn't load.

[ERROR] lua/lua_screens/screens/rnd3.lua:26: attempt to index a nil value
  1. recursecomments - lua/lua_screens/screens/rnd3.lua:26
   2. recursecomments - lua/lua_screens/screens/rnd3.lua:48
    3. recursecomments - lua/lua_screens/screens/rnd3.lua:48
     4. recursecomments - lua/lua_screens/screens/rnd3.lua:48
      5. recursecomments - lua/lua_screens/screens/rnd3.lua:48
       6. recursecomments - lua/lua_screens/screens/rnd3.lua:48
        7. recursecomments - lua/lua_screens/screens/rnd3.lua:48
         8. recursecomments - lua/lua_screens/screens/rnd3.lua:48
          9. recursecomments - lua/lua_screens/screens/rnd3.lua:48
           10. recursecomments - lua/lua_screens/screens/rnd3.lua:48
            11. recursecomments - lua/lua_screens/screens/rnd3.lua:48
             12. recursecomments - lua/lua_screens/screens/rnd3.lua:48
              13. recursecomments - lua/lua_screens/screens/rnd3.lua:48
               14. recursecomments - lua/lua_screens/screens/rnd3.lua:4

Bug reported by '<color=0,191,255>Yagira' (STEAM_0:1:80004288).

**Comment by notcake** [comment]
you're holding it wrong

**Comment by PotcFdk** [comment]
duplicate of #200
