### ISSUE TITLE
Getting up from Sit Anywhere causes crazy physics with equipped inventory

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#216]
Repro:
Equip something in inventory
Sit anywhere
Get up (Triggering crazy physics and losing the item)

Thank you for the fine server that is metastruct.
Glad to help.

Bug reported by 'PlNG' (STEAM_0:1:27456944).

**Comment by Python1320** [comment]
@Xerasin

**Comment by Myaats** [comment]
fixed with Metastruct/Sit-Anywhere@ff5230abf5a3a068bad37c0e45f61f6df880f932
