### ISSUE TITLE
banni

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#218]
even tenrys banned me with the dumb reason "alt of bjoern90" i can still run luas with lua_openscripct_cl https://i.imgur.com/JSR3eO5.jpg also can i get unbanned from bug reporter on my real account?

Bug reported by '^7Shekel Man' (STEAM_0:0:147724421).

**Comment by Tenrys** [comment]
no

**Comment by KabusDev** [comment]
shoo

**Comment by PotcFdk** [comment]
Can somebody explain what this means?

**Comment by Tenrys** [comment]
bjoern wants his alt unbanned and to be able to report bugs on github with his real account again

**Comment by PotcFdk** [comment]
Is that the entire purpose of this issue? There was something related to lua_openscript_cl, which was what I was referring to.

**Comment by Tenrys** [comment]
I guess he's saying the issue is that he can still run clientside Lua when banned using lua_openscript_cl.

**Comment by PotcFdk** [comment]
I'll deal with the blacklist thing,
@Python1320 review the Lua running issue (if it's okay to run Lua while banned, that's an acceptable resolution, too, but pls post one kthx)

**Comment by PotcFdk** [comment]
Unblacklisted.

**Comment by Etothepowerof26** [comment]
i thought you could still run lua editor scripts while your banned
last time i tried was when i got banned from rtd

**Comment by Python1320** [comment]
You are allowed to run lua while banned. Making it not possible is impossible as you could have added a command before, before being restricted, that runs lua.
