### ISSUE TITLE
Chatbubbles err

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#22]
Player [23][Qidrokun] ERR: [Hook] PostDrawTranslucentRenderables -> "Chatbubbles" failed: lua/autorun/chatbubbles.lua:72: Tried to use a NULL entity!

Bug reported by 'Python1320' (STEAM_0:0:13073749).

**Comment by LUModder** [comment]
Pinging @Tenrys since he made them

**Comment by Tenrys** [comment]
fixed by kraken as he remade everything
