### ISSUE TITLE
adding a item to backpack many times before its removed seems to duplicate the item

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#220]
```lua
hook.Add('Think', 'hahatest', function()
	for i, v in pairs(ents.FindByClass('coke_item_sent')) do
		v:CallOnServer('__options', '', '__backpack', 'start')
	end
end)
```
to reproduce it

![and a gif of it working](https://my.mixtape.moe/dgkbsw.gif)

Bug reported by '<color=231,10,46,225>loser' (STEAM_0:1:104332977).

**Comment by Myaats** [comment]
Should be fixed from the next server restart, feel free to reopen if the problem persists
