### ISSUE TITLE
e2ignore

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#221]
e2ignore #all errors

[Hook] ChatCommand -> "ignoree2" failed: lua/autorun/client/richtextx.lua:306: bad argument #3 to 'InsertColorChangeReal' (number expected, got function)

Bug reported by 'loser' (STEAM_0:1:104332977).

**Comment by Myaats** [comment]
it's because #all resolves to a  metatable with __call with player's not e2 chips.
not a bug, it's a feature
