### ISSUE TITLE
Strange entity lag from Starfall

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#225]
in other servers starfall can do o(n) gravity with applyForceCenter without much of a problem, but in meta it is laggy.

possible causes:
- debug.sethook infinite loop protection
- bad metatables on entities
- easylua doing strange things
- detours
- snakes
- c++ modules
- :cactus:
- meta using old sf code
- penetration testing (not the spooky kind)

**Comment by ajloveslily14** [comment]
My best guess is 🌵

**Comment by EgrOnWire** [comment]
![cactus](http://onlycactus.ru/wp-content/uploads/2008/05/echinocactus_grus.jpg)

**Comment by BlueCyro** [comment]
You're gonna have to describe it better than just "laggy". It seems to work fine.

**Comment by Myaats** [comment]
Metastruct has a lot of code detouring everything physics related for doing sanity checks. Do not expect this to get better any time soon

**Comment by PotcFdk** [comment]
- reduced tick rate

**Comment by Python1320** [comment]
Located reason for this most likely (aowl/groups.lua). Closing this when I've fixed them. Make a new ticket if still a problem after that.

Debug info:
```lua

| 1     lua/aowl/groups.lua:117: GetUserGroup
| 2     lua/aowl/groups.lua:53: IsSuperAdmin
| 3     lua/starfall/permissions/providers_sh/entity.lua:32: v
| 4     lua/starfall/permissions/core.lua:106: ?
| 5     lua/starfall/permissions/core.lua:69: checkpermission


| 0     lua/includes/extensions/player.lua:-1: __index
| 1     lua/autorun/sh_playingtime.lua:68: GetUTimeTotalTime
| 2     lua/aowl/groups.lua:58: IsSuperAdmin
| 3     lua/starfall/permissions/providers_sh/entity.lua:32: v
| 4     lua/starfall/permissions/core.lua:106: ?
| 5     lua/starfall/permissions/core.lua:69: checkpermission

```

**Comment by ghost** [comment]
Still relevant?

**Comment by cdr1996** [comment]
Old issue, no one responding to it. Assumed fixed or dealt with since last comment was around 3 years ago. Reopen if still a problem.
