### ISSUE TITLE
Expression2 coin extension errors

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#228]
When you use moneyRequest() an error gets thrown, code used is here

    Player = owner()
    moneyRequest(Player,1)

error thrown is

    sv: Expression 2 (generic): entities/gmod_wire_expression2/core/custom/sv_moneyrequest_tylerb.lua:49: attempt to index global 'caller' (a nil value)

Note that every variation of the function errors, and requesting from other players also throws the error

Bug reported by '<c=FFFF00>Some<hsv=[t()*150]>_<c=FFFF00>Beach' (STEAM_0:1:55684109).

**Comment by Myaats** [comment]
I guess this is related to the cooldown feature added by @ToastyEngineer some days ago

**Comment by Tenrys** [comment]
Yes

**Comment by Myaats** [comment]
should be fixed after next rehash + server restart, re-open if the issue presists
