### ISSUE TITLE
Chatsounds throwing error when typing in chat

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#232]
[Hook] PostRenderVGUI -> "chatsounds_autocomplete" failed: lua/includes/enum/fontsex.lua:20: attempt to index local 'k' (a number value)
    stack traceback:
    lua/includes/enum/fontsex.lua:20: in function 'CreateFont'
    lua/chatsounds/capsadmins_font_cache_thing.lua:7: in function 'create_fonts'
    lua/chatsounds/capsadmins_font_cache_thing.lua:55: in function 'chatsounds_DrawPrettyText'
    lua/chatsounds/autocomplete.lua:169: in function 'render'
    lua/chatsounds/autocomplete.lua:321: in function 'func'
    lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156>
    [C]: in function 'xpcall'
    lua/includes/modules/hook.lua:213: in function <lua/includes/modules/hook.lua:194>

Not sure what could have caused this, I don't think there were any recent changes in the autocomplete part were there

Bug reported by '<c=FFFF00>Some<hsv=[t()*150]>_<c=FFFF00>Beach' (STEAM_0:1:55684109).

**Comment by ajloveslily14** [comment]
update: it seems to have to do with fonts alltogether

```
[ERROR] lua/includes/enum/fontsex.lua:20: attempt to index local 'k' (a number value)
  1. CreateFont - lua/includes/enum/fontsex.lua:20
   2. CreateFont - lua/entities/gmod_wire_textscreen.lua:205
    3. unknown - lua/entities/gmod_wire_textscreen.lua:130

[NET] wire_netmsg_registered: lua/includes/enum/fontsex.lua:20: attempt to index local 'k' (a number value)
stack traceback:
	lua/includes/enum/fontsex.lua:20: in function 'CreateFont'
	lua/entities/gmod_wire_textscreen.lua:205: in function 'CreateFont'
	lua/entities/gmod_wire_textscreen.lua:186: in function 'Receive'
	lua/wire/wireshared.lua:457: in function <lua/wire/wireshared.lua:455>
	[C]: in function 'xpcall'
	lua/includes/extensions/net.lua:84: in function <lua/includes/extensions/net.lua:56>
```

**Comment by ajloveslily14** [comment]
nevermind it turns out im retarded and just needed to relog
