### ISSUE TITLE
Remove the HSV sin color (aka. rainbow)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#235]
The problem is these rainbow names can be annoying to your eyes.
You can make the limit or remove the sin completely. Thanks in advance.

Bug reported by '<c=FFD777>innoJ' (STEAM_0:1:62957165).

**Comment by ghost** [comment]
or make hsv names not appliable to nicks

**Comment by Vahinkolaukausosuma** [comment]
chathud_markup_hsv 0

**Comment by ghost** [comment]
ok thanks

**Comment by Vahinkolaukausosuma** [comment]
h

**Comment by Myaats** [comment]
Use the convar as already mentioned to disable it
