### ISSUE TITLE
"rnd3" lua screen bug on #2

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#236]
[ERROR] lua/lua_screens/screens/rnd3.lua:26: attempt to index a nil value
  1. recursecomments - lua/lua_screens/screens/rnd3.lua:26
   2. recursecomments - lua/lua_screens/screens/rnd3.lua:48
    3. recursecomments - lua/lua_screens/screens/rnd3.lua:48
     4. recursecomments - lua/lua_screens/screens/rnd3.lua:48
      5. recursecomments - lua/lua_screens/screens/rnd3.lua:48
       6. recursecomments - lua/lua_screens/screens/rnd3.lua:48
        7. recursecomments - lua/lua_screens/screens/rnd3.lua:48
         8. recursecomments - lua/lua_screens/screens/rnd3.lua:48
          9. recursecomments - lua/lua_screens/screens/rnd3.lua:48
           10. recursecomments - lua/lua_screens/screens/rnd3.lua:48
            11. recursecomments - lua/lua_screens/screens/rnd3.lua:48
             12. recursecomments - lua/lua_screens/screens/rnd3.lua:48
              13. recursecomments - lua/lua_screens/screens/rnd3.lua:48
               14. recursecomments - lua/lua_screens/screens/rnd3.lua:48
                15. recursecomments - lua/lua_screens/screens/rnd3.lua:48
                 16. recursecomments - lua/lua_screens/screens/rnd3.lua:48

Bug reported by '<c=FFD777>innoJ' (STEAM_0:1:62957165).

**Comment by bjoern90** [comment]
cuz you're playing on old map

**Comment by ghost** [comment]
Problem figured out, you can close the issue.
