### ISSUE TITLE
CMaterial::DrawElements: No bound shade

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#237]
CMaterial::PrecacheVars: error loading vmt file for sunabouzu/elevator_roof
CMaterial::PrecacheVars: error loading vmt file for sunabouzu/elevator_roof
CMaterial::PrecacheVars: error loading vmt file for sunabouzu/elevator_roof
CMaterial::PrecacheVars: error loading vmt file for sunabouzu/elevator_roof
CMaterial::PrecacheVars: error loading vmt file for sunabouzu/elevator_roof
CMaterial::PrecacheVars: error loading vmt file for sunabouzu/elevator_roof
CMaterial::DrawElements: No bound shader

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by Myaats** [comment]
This is probably related to the material being packaged in the map file I guess

**Comment by Python1320** [comment]
Most likely fixed with the new bundling code
