### ISSUE TITLE
Scoreboard - Tooltip on Ping/AFK Column

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#24]
The Tooltip Text on the Ping/AFK Column (last Column) does not change according to the information it shows (Ping or AFK Time), it only states "Ping" no matter what it shows.

Bug reported by '<color=255,120,0>Google' (STEAM_0:1:66459838).

**Comment by LUModder** [comment]
Error spam at all of IsAFK being null?

**Comment by Cynosphere** [comment]
Fixed in srvaddons 11547
