### ISSUE TITLE
masks is shit

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#241]
https://i.imgur.com/HJa8wxS.png the :stop: is the red stopsign but no "pinkguy" in chat and the trollface is like a steamicon maybe a fix could be gud

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by bjoern90** [comment]
the trollface looks like this in chat https://i.imgur.com/Iyekirc.png

**Comment by Myaats** [comment]
can you please describe the issue properly, this just looks like a shitpost

**Comment by ghost** [comment]
Well, he wants an "trollface" emote and "pinkguy" emote, because for some/most part of the emotes are from Steam.
(so sorry)

**Comment by aminpeck** [comment]
Essentially, what he's expecting is something like https://i.imgur.com/ErDhYfP.png (the Discord server emote) but he instead gets https://i.imgur.com/PlnSfsu.png (the standard Garry's Mod emote).

**Comment by Tenrys** [comment]
The :trollface: mask is something I added a long time ago for some reason when I thought it was funny.
(and for some reason it's a thing on github?)

**Comment by ghost** [comment]
tenrys isn't joking, that is a thing on github https://assets-cdn.github.com/images/icons/emoji/trollface.png

**Comment by Tenrys** [comment]
![](https://tenrys.pw/ShareX/2018/Feb/2tJf.png)

**Comment by Myaats** [comment]
fixed with revision 14462
