### ISSUE TITLE
Achievement: traveller

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#243]
Check the status of the traveller achievement and/or update the server list.

**Comment by ajloveslily14** [comment]
Currently the achievement requires you to have visited servers 1,2 and 3 which I believe doesn't exist.

**Comment by ghost** [comment]
3rd server exists.
http://sharex.wicop33.xyz/hl2_2018-02-20_22-45-35.png

**Comment by ghost** [comment]
But I'm pretty sure it doesn't run code for achievements and other MetaWorks stuff.

**Comment by PotcFdk** [comment]
Apparently that achievement module just uses MetaWorks' server list, which has recently been updated/fixed.
