### ISSUE TITLE
Achievement: Grove Street Tag

### ISSUE THREAD

**Issue by ajloveslily14** [Metastruct/issues#245]
Doesn't seem to be catching people placing sprays between the cords, and on m3ta the cords are in the world to it can't be gotten

**Comment by PotcFdk** [comment]
@Techbot121 didn't you change the coordinates recently? Maybe take a look at it if you want. You don't have to, though.

**Comment by Techbot121** [comment]
yea I was planning on using a landmark later though

**Comment by ajloveslily14** [comment]
Seems fixed, at least on the original meta map. Not on M3 though.

**Comment by PotcFdk** [comment]
Shouldn't this be open, then? M3 is considered the main thing now, isn't it?

**Comment by ajloveslily14** [comment]
I am not sure, from what I understand M3 is the beta map

**Comment by PotcFdk** [comment]
Reopening until somebody (could be me) confirms it works like you'd expect it to work.

**Comment by PotcFdk** [comment]
Fixed.
