### ISSUE TITLE
inventory bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#246]
why do i see this when i do print table on my iventory
https://i.imgur.com/XnP14cU.png
when i see this as nothing at all?
https://i.imgur.com/tCLtcoa.png

why not just clean up when there's no such as item name?

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Myaats** [comment]
in case it was just a loading bug auto deleting non-existant inventory items is really risky, so this is not a bug
