### ISSUE TITLE
map televator bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#247]
https://i.imgur.com/St2vL0e.png
Room: Management

Bug reported by '<color=225,70,95>zocyri' (STEAM_0:1:62957165).

**Comment by Myaats** [comment]
![image](https://user-images.githubusercontent.com/6295090/36641417-681efaa0-1a2f-11e8-9406-6c3c36f553f4.png)
I guess you have to wait for the next map compile
