### ISSUE TITLE
lua/entities/propellerengine/cl_init.lua:285: bad argument #1 to 'max' (number expected, got nil)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#248]
[ERROR] lua/entities/propellerengine/cl_init.lua:285: bad argument #1 to 'max' (number expected, got nil)
  1. max - [C]:-1
   2. CalculateSounds - lua/entities/propellerengine/cl_init.lua:285
    3. unknown - lua/entities/propellerengine/cl_init.lua:328

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by PotcFdk** [comment]
Line is in `ENT:CalculateSounds()`:
```Lua
self.smoothsoundpitch = Lerp(0.05,math.max(self.smoothsoundpitch,0.001),pitch)
```

which is set in `ENT:Initialize()`. Weird.
On a second glance, `ENT:Initialize()` exits early if the player entity is invalid:
```Lua
if not IsValid(ply) then return end
```

However, `ENT:CalculateSounds()` is called from `ENT:Think()`, which also exits early if the entity is invalid:
```Lua
local ply = self.dt.ply
if not IsValid(ply) then return end
```

I'll take a wild guess that this was just a very unlucky race condition. Re-open if anybody sees this again.
