### ISSUE TITLE
[Hook] CanPlyGoto -> "ms" failed: lua/metastruct/logics/sv_restrictions.lua:6: attempt to index a string value with bad key ('IsValid' is not part of the string library)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#249]
[Hook] CanPlyGoto -> "ms" failed: lua/metastruct/logics/sv_restrictions.lua:6: attempt to index a string value with bad key ('IsValid' is not part of the string library)
stack traceback:
        [C]: in function 'error'
        lua/includes/extensions/string.lua:297: in function '__index'
        lua/metastruct/logics/sv_restrictions.lua:6: in function 'func'
        lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156>
        [C]: in function 'xpcall'
        lua/includes/modules/hook.lua:213: in function 'Run'
        lua/aowl/aowl.lua:437: in function <lua/aowl/aowl.lua:414>
        [C]: in function 'xpcall'
        lua/aowl/aowl.lua:202: in function <lua/aowl/aowl.lua:190>
        [C]: in function 'pcall'
        lua/aowl/aowl.lua:190: in function 'CallCommand'
        lua/aowl/commanddispatcher.lua:12: in function <lua/aowl/commanddispatcher.lua:3>
        [C]: in function 'xpcall'
        lua/includes/modules/concommand.lua:94: in function 'InjectConsoleCommand'
        lua/autorun/server/maprestartgoto.lua:61: in function 'func'
        lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156>
        [C]: in function 'xpcall'
        lua/includes/modules/hook.lua:213: in function <lua/includes/modules/hook.lua:194>

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by PotcFdk** [comment]
Seems to be fixed by @Techbot121 in `metastruct@2cfbe1eca082cf903200a06201b64309b658d84e`
