### ISSUE TITLE
Tremble broken

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#25]
[15:46] lua/metastruct/logics/sh_restrictions.lua:81: Tried to use a NULL entity!
  1. __newindex - [C]:-1
   2. SetAllowNoclip - lua/metastruct/logics/sh_restrictions.lua:81
    3. unknown - lua/minigames/games/tremble/sv_tremble.lua:336

People can't noclip if a game is made and it breaks

Bug reported by 'Flex' (STEAM_0:0:58178275).

**Comment by PotcFdk** [comment]
@TheFreezebug maybe?

**Comment by LUModder** [comment]
Lixquid and @Tenrys were the last this work on it

**Comment by PotcFdk** [comment]
So let's also ping @Lixquid and hope one of them fixes it :rainbow:

**Comment by Lixquid** [comment]
I've literally never touched the base game.

The base game's pants, which is why I rewrote it.

My rewrite is also pants, which is why I never pushed it.

**Comment by Tenrys** [comment]
Fixed since then I think
