### ISSUE TITLE
Small-sized PAC's lets you get through the MSA room entrance

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#250]
How to:
1. Make a small-sized PAC. (size < 1)
2. Slowly walk to the entrance, so you'll stand next to the entrance.
3. Run and quickly `aowl tp`

**Comment by loserVEVO** [comment]
Literally unplayable, this fix resolves all issues and fixes uptime.

**Comment by ajloveslily14** [comment]
seems fixed
