### ISSUE TITLE
lua/msascripts/area_access_cards.lua:29: attempt to index local 'weapon' (a nil value)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#251]
lua/msascripts/area_access_cards.lua:29: attempt to index local 'weapon' (a nil value)
  1. MSAHasAccess - lua/msascripts/area_access_cards.lua:29
   2. func - lua/metastruct/triggers/msa_area.lua:16
    3. unknown - lua/entities/lua_trigger_base/init.lua:290

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by PotcFdk** [comment]
Should be fixed.
