### ISSUE TITLE
lua/entities/ent_fallingplat

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#252]
lua/entities/ent_fallingplatform/init.lua:370: attempt to index field 'GhostEnt' (a nil value)
  1. SPGhostOut - lua/entities/ent_fallingplatform/init.lua:370
   2. LosePlate - lua/entities/ent_fallingplatform/init.lua:436
    3. unknown - lua/entities/ent_fallingplatform/init.lua:399

Bug reported by 'noyesthat' (STEAM_0:1:62957165).

**Comment by bjoern90** [comment]
and remove this spam 
Crazy origin on entity [-1][class C_BaseFlex]
	Origin:           [3577.468750, 2559.468750, -16389.818359]
	Angles:           [-67.891403, 32.018303, 329.997223]
	Velocity:         [0.000000, 0.000000, -1165.715088]
	Angular Velocity: [7.800922, 51.225674, -2.549795]
Defusing!
Removing!
 blame nak anyways

**Comment by ghost** [comment]
Sorry, @bjoern90 , but your comment was removed, because the comment is not linked in any way to this issue.
Create an separate issue instead.

View the comment here: http://sharex.wicop33.xyz/chrome_2018-02-28_22-47-32.png

**Comment by bjoern90** [comment]
eugh k

**Comment by PotcFdk** [comment]
@Nak2

**Comment by Nak2** [comment]
I'll take a look at it. Atm I think its best to remove the minigame, as it isn't the only bug reported and I kinda burned out on StormFox support. I'll look at it in this weekend.

**Comment by ghost** [comment]
Was this ever fixed?

**Comment by ghost** [comment]
Looks like it's since been removed from the server so I'm going to go ahead and close this.
