### ISSUE TITLE
rp shit

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#253]
the advent thing still shows when gagging ppl https://i.imgur.com/zWZoaVR.png

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by ajloveslily14** [comment]
You can only advert and ooc once per session anyways, who cares. Instead of being petty, learn to ignore people. Most have for you.

**Comment by bjoern90** [comment]
salty as always

**Comment by PotcFdk** [comment]
>Who cares

Well, if it's a bug/not intended, we should. If it is not, why not just close instead of `whiny-cunts`?

**Comment by bjoern90** [comment]
yes its a bug do you think its a shitpost?

**Comment by ghost** [comment]
It's not a bug, neither shitpost.
Can you please learn how to ignore people?

**Comment by bjoern90** [comment]
how can i when they’re gagged?

**Comment by ghost** [comment]
> ignore

**Comment by bjoern90** [comment]
#DevsDontGiveAFuckAboutBugs

**Comment by ghost** [comment]
> It's not a bug, neither shitpost.

**Comment by aminpeck** [comment]
I highly suggest that this issue be closed, as this is not considered a bug, plus the conversation has **spiralled out of control.**
