### ISSUE TITLE
[NET] poll: lua/includes/extensions/net.lua:249: net.ReadType: Couldn't read type 83

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#254]
[NET] poll: lua/includes/extensions/net.lua:249: net.ReadType: Couldn't read type 83
stack traceback:
	[C]: in function 'error'
	lua/includes/extensions/net.lua:249: in function 'ReadType'
	lua/includes/extensions/net.lua:190: in function 'ReadTable'
	lua/lua_screens/screens/poll.lua:511: in function <lua/lua_screens/screens/poll.lua:508>
	[C]: in function 'xpcall'
	lua/includes/extensions/net.lua:84: in function <lua/includes/extensions/net.lua:56>
Player [17][ioee] ERR: [NET] poll: lua/includes/extensions/net.lua:249: net.ReadType: Couldn't read type 83
stack traceback:
	[C]: in function 'error'
	lua/includes/extensions/net.lua:249: in function 'ReadType'
	lua/includes/extensions/net.lua:190: in function 'ReadTable'
	lua/lua_screens/screens/poll.lua:511: in function <lua/lua_screens/screens/poll.lua:508>
	[C]: in function 'xpcall'
	lua/includes/extensions/net.lua:84: in function <lua/includes/extensions/net.lua:56>

Bug reported by 'noyesthat' (STEAM_0:1:62957165).

**Comment by Myaats** [comment]
@Tenrys

**Comment by azephiris** [comment]
self.author = nil when loading polls that doesn't have author nick

**Comment by Tenrys** [comment]
i bet the server didn't even restart

**Comment by ghost** [comment]
fixed with revision 3599
