### ISSUE TITLE
spamming scap bind and exiting scap will cause screen to "stick"

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#255]
having a key bound to "scap" and spamming the bind while also exiting scap will cause the screen brought up by scap to stick; disconnect to fix

Bug reported by '<color=51,0,221>homonovus' (STEAM_0:0:41908082).

**Comment by Cynosphere** [comment]
Can confirm for all the following:
- SCAP bind spam
- imgur bind spam
- SCAP + viewflip
- imgur + viewflip

Issue: RenderScene hook not going away on exit properly

(also you dont need to reconnect to fix, just remove RenderScene.scap and/or RenderScene.imgur)

Undoing hook breaks the following RenderScene hooks:
- RenderScene.highperf: lua/chatbox/tab_lua.lua: 70-114

**Comment by cdr1996** [comment]
Old issue, unsure if fixed by anyone. Either way, its a small visual clientside problem, unlikely to cause any real harm to anyone. Rather a nitpick I guess, so I guess I'll keep this open in case someone wants to fix it (if not already fixed).

**Comment by cdr1996** [comment]
Stale, closed
