### ISSUE TITLE
goto locations are messed up

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#257]
when i go to the "fish", instead of sending me to the fishing area, it sends me somewhere in the lobby.
when i type fully "fishing", it sends me to random player??

Bug reported by ':you:' (STEAM_0:1:62957165).

**Comment by bjoern90** [comment]
cuz there's no fishing area on m3ta map https://i.imgur.com/TfZHTzQ.png

**Comment by bjoern90** [comment]
https://i.imgur.com/nZGJcgG.png knew it there's no goto fish marks

**Comment by Myaats** [comment]
Bjoern is right
