### ISSUE TITLE
Screen error (Entity [1973][lua_screen], rnd1): (ERR) lua/demomen/captcha.lua:7: attempt to call global 'PrecacheArc' (a nil value)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#258]
Screen error (Entity [1973][lua_screen], rnd1): (ERR) lua/demomen/captcha.lua:7: attempt to call global 'PrecacheArc' (a nil value)

Bug reported by 'Some_Beach' (STEAM_0:1:55684109).

**Comment by ajloveslily14** [comment]
no error anymore but it doesn't render so..
