### ISSUE TITLE
FOV Bug.

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#259]
When you ever do the FOV command. It resets when you equip any SWEP (switch from weapons) 

Bug reported by '<hsv=[time()*1e6]>Kai' (STEAM_0:0:37634106).

**Comment by loserVEVO** [comment]
Literally unplayable, this fix resolves all issues and fixes uptime.

**Comment by Techbot121** [comment]
whatever,

Only fix I can see for this is by checking for the fov override in sh_visuals.lua

**Comment by cdr1996** [comment]
Old issue, not likely to cause any real harm, just a visual thing. Marked as low priority, if someone wants to fix go ahead.

**Comment by cdr1996** [comment]
Stale so closing
