### ISSUE TITLE
[Usermessage] Unhandled message 'msitems.NPCShopSay'

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#26]
I've no idea where its coming from but I just found this in my Console.

Bug reported by '<color=255,120,0>Google' (STEAM_0:1:66459838).

**Comment by GurgleOS** [comment]
[Usermessage] Unhandled message 'msitems.NPCShopSay' (randomly)
[Usermessage] Unhandled message 'gauth_notification' (directly after I joined the Server)

**Comment by PotcFdk** [comment]
Pinging @notcake for the latter message.

**Comment by notcake** [comment]
E_WONTFIX | E_PENDING_ANTITRUST_LAWSUIT

**Comment by PotcFdk** [comment]
Is this still relevant?

**Comment by ghost** [comment]
I don't think so, I haven't noticed it at least.
