### ISSUE TITLE
Mine entry hole visleafs

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#261]
When you're high enough, it looks like this, which is fine I guess
![grafik](https://user-images.githubusercontent.com/3160048/37171988-d68e9c78-230f-11e8-99fe-468e1d679c04.png)
but further down, it turns invisibru
![grafik](https://user-images.githubusercontent.com/3160048/37172028-f481f1a8-230f-11e8-966f-673e08765fb6.png)
\<engage mode="project manager"\>I'm not a mapper, but can't you get that top part included in the relevant visleaf to make it look better?\</engage\>

**Comment by ajloveslily14** [comment]
I think that's because it's an area portal

**Comment by Earu** [comment]
@PotcFdk I do believe this is because the mines are their own instance, and for performance sake a closed area portal was put there.

**Comment by ajloveslily14** [comment]
Rent free too!
