### ISSUE TITLE
Banned players are capable of votekicking other players.

### ISSUE THREAD

**Issue by aminpeck** [Metastruct/issues#262]
It has recently come to my attention that banned players are capable of votekicking other players, **despite the fact that they are clearly banned**. Bug or not, this is something that should be fully addressed and patched if possible.

**Comment by ajloveslily14** [comment]
I'll fix it as soon as my game loads lol

**Comment by ajloveslily14** [comment]
Seems to already be in, not sure wtf happened

**Comment by aminpeck** [comment]
Considering this closed until the bug arises again.
