### ISSUE TITLE
Bouncing back while bhopping

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#263]
Lately I've noticed that you get pushed/bounced back while bhopping, seemingly randomly.
Is this a bug or a feature?
If it's a feature, provide an option to revert back to the old behavior.

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by ghost** [comment]
I'm pretty sure the issue was causing SpiralP's persistent lua script.
Check EPOE logs when the player spawns.

**Comment by Myaats** [comment]
I think this is the double jump script, iirc someone removed the sound from it

**Comment by ajloveslily14** [comment]
It's been like this for a while now, it plays the sound as if you were looking straight down.

**Comment by homonovus** [comment]
this has been a thing since i first came on in like, 2016
the only thing that's changed is its sensitivity when hitting walls

**Comment by PotcFdk** [comment]
This has definitely not been the case in 2016 @homonovus 
@WicopeeDot ugh, good point, that's plausible.
@SpiralP was that you?

**Comment by Techbot121** [comment]
no this did happen before, only when autobhop was disabled and you pressed space right when you were about to hit a wall. But yeah it seems as if it's behaving the same as on the PAC server.

**Comment by PotcFdk** [comment]
I wonder why I never noticed this before, then. Weird. Must be some kind of extreme case of the mandala effect.
