### ISSUE TITLE
coin(to those who cares about it)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#264]
there's no auto coin spawn witch sera added it for a week ago and now there's none..
someone fix it?

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by loserVEVO** [comment]
very detailed, thanks for the issue. will be fixed in the next couple decades.

**Comment by Tenrys** [comment]
What does that mean in English?

**Comment by Zeni44** [comment]
From what I've seen in the commits, random coin spawning hasn't been touched in a longer while.
Whatever Sera ran wasn't pushed to the repository unless I missed something.

If you mean something else then I can't make out what you mean.

**Comment by bjoern90** [comment]
yep toasty is right
