### ISSUE TITLE
SQL db could use some vacuuming

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#266]
But `VACUUM` results in a syntax error, as does `PRAGMA`.
@Python1320 do you know if the server uses a much, much older and/or restricted version of sqlite compared to clients (where `PRAGMA` works)?
Might need to vacuum out-of-band. Not sure if the bang per buck is high enough to bother.

**Comment by PotcFdk** [comment]
Update: tried it locally, reduced from 66M down to 58M, I guess it's not really worth the hassle at the moment.

**Comment by PotcFdk** [comment]
Reopened this because the size has increased since. Statistics that I created a short while ago have shown that it's mediaplayer's fault for dumping all metadata and history into `sv.db`.
@Python1320 you alluded to the idea that it might slow down some things. How severe is it, do you think?
Plus, the question regarding the sqlite version from the issue OP still stands. I'll keep this open so I (or somebody else) remembers to investigate this.

**Comment by ajloveslily14** [comment]
There's a 1-2 second long lag spike when a new player joins. I'm assuming it's from sql

**Comment by cdr1996** [comment]
If I remember, this was only on server #1, which I believe (correct me if I'm wrong) was running on bad hardware or something along those lines. Server #2 which is the current one in use doesn't seem to suffer from said issue. Reopen if needed, otherwise case closed I guess.
