### ISSUE TITLE
New playtime badge levels

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#271]
Currently, we have these:

```Lua
	{ time =    2*hour, id =    "2h", title = "Guest" },
	{ time =    5*hour, id =    "5h", title = "Beginner" },
	{ time =   10*hour, id =   "10h", title = "Basic" },
	{ time =   25*hour, id =   "25h", title = "Member" },
	{ time =   50*hour, id =   "50h", title = "Advanced" },
	{ time =  100*hour, id =  "100h", title = "Pro" },
	{ time =  250*hour, id =  "250h", title = "Premium" },
	{ time =  500*hour, id =  "500h", title = "Ultimate" },
	{ time =  750*hour, id =  "750h", title = "Addict" },
	{ time =  999*hour, id =  "999h", title = "CapsAdmin" },
	{ time = 2000*hour, id = "2000h", title = "Eternal Devotion" },
```

TODO:

- [x] Figure out what the currently existing playtime records are
- [ ] Figure out how many (and which) new levels would make sense.
- [ ] Make new icons for these new levels (**help wanted**)

**Comment by Tenrys** [comment]
I don't see anything wrong with the current ranks, why change?

**Comment by PotcFdk** [comment]
Because there are players with way more hours. Currently 2000 hours is the maximum level, we could add some more? This has been requested in the past, at least..

**Comment by Cynosphere** [comment]
I propose at least two

5000 - Time Waster, No Life or something of that nature
10000 - Python1320, as he has the most hours out of everyone and surpassed 10k a while ago

**Comment by PotcFdk** [comment]
That sounds good so far. Perhaps a 7500 one wouldn't hurt, too.
Suggestions for alternative naming? -> post here
Want to create icons? post here or private message me

**Comment by PotcFdk** [comment]
Closing this because [there seems to be less need for it than I initially assumed](http://g2.metastruct.net:20080/metabadges/), we seem to have a good distribution.
