### ISSUE TITLE
theatre cubemaps

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#272]
reflections in theatre relate to corridoor outside theatre and the televator, add a cubemap for theatre

Bug reported by '<color=255,100,255>kabus' (STEAM_0:1:39423581).

**Comment by PotcFdk** [comment]
Still relevant, now that we are on m3?

**Comment by ajloveslily14** [comment]
It would seem so, yes.

**Comment by PotcFdk** [comment]
@Metastruct/mappers

**Comment by cdr1996** [comment]
3 years old, still relevant?

**Comment by cdr1996** [comment]
Assuming fixed since no replies have been made and issue is old so probably no longer relevant, reopen if not fixed.
