### ISSUE TITLE
newlines are allowed in nicknames

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#275]
how could one man have slipped through your forces fingers time and time again how is it possible this is not some agent provocateur or highly trained assassin we are discussing gordon freeman is a theoretical physicist who had hardly earned the distinction of his phd at the time of the black mesa incident i have good reason to believe that in the intervening years he was in a state that precluded further development of covert skills the man you have consistently failed to slow let alone capture is by all standards simply that an ordinary man how can you have failed to apprehend him

Bug reported by 'Frumorn﻿' (STEAM_0:1:104332977).

**Comment by Zeni44** [comment]
Fixed
