### ISSUE TITLE
rp chat shits bypasses the gag

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#276]
ppl can still send me messages with rp occ/ads n shit https://i.imgur.com/0PMo2fe.png getting triggered how loser wont stop leaving me alone for some reason.

Bug reported by '<color=255,255,255><se=coin20cent>^7Bjoern⁹⁰' (STEAM_0:1:42844056).

**Comment by loserVEVO** [comment]
how do engles yes

**Comment by jule14** [comment]
Why does /ooc or /advert even exist

**Comment by ajloveslily14** [comment]
I feel like this is the second time you've posted this. /ooc and /advert can only be used once per login anyways, stop being so petty and get over it.

**Comment by bjoern90** [comment]
but how did loser spam it? :thonk:

**Comment by Etothepowerof26** [comment]
6

**Comment by ajloveslily14** [comment]
he was able to spam because the command was changed temporarily
