### ISSUE TITLE
je ne peux pas jouer sa lag trop au départ apres sa va bien 

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#28]
la réponse est dans le titre

Bug reported by 'Herogamer' (STEAM_0:0:1755655664).

**Comment by PotcFdk** [comment]
I tried to fix the french and then translate it: "I can not play, it's too laggy initially. After that, it's fine."
I think he meant the spawn lag.
Obligatory @Python1320 ping.
Closing this; reopen if necessary.
