### ISSUE TITLE
hoverbike messes up your arm and leg angles sometimes?

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#280]
hoverbike messes up your arm and leg angles sometimes?

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by SpiralP** [comment]
http://put.nu/files/CQ0G3YV.png

**Comment by SpiralP** [comment]
![2018-07-21_02-32-52](https://user-images.githubusercontent.com/2898730/43034275-6e0702ec-8c8e-11e8-8d15-9ce4ba048500.png)

**Comment by Earu** [comment]
Should not happen anymore now, if it keeps doing it blame pac3.
