### ISSUE TITLE
lua/autorun/server/penicillium.lua:15: attempt to call method 'SetAllowBuild' (a nil value

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#281]
when not on a metastruct map

```
lua/autorun/server/penicillium.lua:15: attempt to call method 'SetAllowBuild' (a nil value)
  1. unknown - lua/autorun/server/penicillium.lua:15
```

`SetAllowBuild` is at lua/metastruct/logics/sh_restrictions.lua:421

@Python1320

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by Python1320** [comment]
Partially fixed. We must move restrictions out of meta codebase.

**Comment by cdr1996** [comment]
@Python1320

**Comment by cdr1996** [comment]
Stale
