### ISSUE TITLE
ERR: NextThink: lua/includes/extensions/entity.lua:104: attempt to index local 'mytable' (a nil value)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#283]
Player [1][combine unicorn:D] ERR: NextThink: lua/includes/extensions/entity.lua:104: attempt to index local 'mytable' (a nil value)
stack traceback:
	lua/includes/extensions/entity.lua:104: in function 'CallOnRemove'
	lua/starfall/sflib.lua:52: in function '__newindex'
	lua/starfall/sflib.lua:52: in function <lua/starfall/sflib.lua:52>
	[C]: in function 'xpcall'
	lua/includes/modules/hookextras.lua:25: in function 'func'
	lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156>
	[C]: in function 'xpcall'
	lua/incl

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by PotcFdk** [comment]
Does this look familiar, @ZehMatt?

**Comment by ghost** [comment]
this happens to me when i timeout

**Comment by ghost** [comment]
Is this still happening?

**Comment by cdr1996** [comment]
I haven't seen this error happen since and it's been a long time since issue was opened, assumed somewhere this has been fixed or for some reason no longer an issue. Reopen if this happens to resurface at some point.
