### ISSUE TITLE
discord relay reconnects every few seconds

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#284]
something to due with the timer at `fast_addons/server/discord.lua:191`, the socket state is sometimes CLOSED

something else that's weird is that it says "Ending websocket connection: closed" more than once but it breaks the loop right after one print so??

```
[Discord] Reconnecting to the websocket server...
[Discord] Connected.
...
[Discord] Ending websocket connection: closed
[Discord] Reconnecting to the websocket server...
[Discord] Connected.
...
[Discord] Reconnecting to the websocket server...
[Discord] Connected.
[Discord] Ending websocket connection: closed
[Discord] Ending websocket connection: closed
...
[Discord] Ending websocket connection: closed
[Discord] Ending websocket connection: closed
...
```

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by Techbot121** [comment]
I tried fixing/redoing that part yesterday, but copas didn't want to be friends with me and I gave up after 2 hours of trying.

**Comment by SpiralP** [comment]
```lua
require("require")
local copas = require("copas")
local websocket = require("websocket")

copas.addthread(function()
	local socket = websocket.client.copas()
	_G.s = socket

	local success, err = socket:connect("ws://echo.websocket.org")
	if not success then
		print('err', err)
		return
	end

	print('connect', success, err, socket)

	while true do
		local data, opcode, was_clean, code, reason = socket:receive()
		print("receive", data)
		if not data then
			print("BREAKING", data, opcode, was_clean, code, reason)
			break
		end
	end

	pcall(function() socket:close() end)
end)

copas.loop()
```

then doing
`!l for k=1,100 do s:send("hi") end` a bunch, you will see an error about yielding without a coroutine (this will not cause the socket to close)

if we wrap the s:send() in a copas.addthread() coroutine
`!l for k=1,100 do copas.addthread(function() s:send("hi") end) end`
it will not error and it will go down the weird math.random() logic at
https://github.com/Metastruct/copas/blob/bd47cfc745d9ea16e3a9ecc007335cf3c5a04489/lua/includes/modules/copas.lua#L285 which will cause the socket to close for some reason

removing that logic altogether fixes the closing bug, but I don't think that's a good solution?

**Comment by SpiralP** [comment]
eh, I just removed the logic, we shouldn't have anything doing "high throughput" in gmod anyways, and if we did it would temporary

https://github.com/Metastruct/copas/commit/25e4c0a4aed621619f47a5112d1e437584b7c1ad
