### ISSUE TITLE
add a !tod off command

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#287]
asdfffffffffffffffffff

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by SpiralP** [comment]
maybe make it clientside?

**Comment by bjoern90** [comment]
many wanted to make tod clinetside and maybe make a tod reset? cuz many devs keeps setting the tod and wont resst when they leave or something.. it triggers me

**Comment by Zeni44** [comment]
Clientside tod won't be possible due to the serverside only function `engine.LightStyle`.
It might be possible with a module? Or workarounds such as messing with the rendering?

**Comment by Etothepowerof26** [comment]
¯\\_(ツ)_/¯

**Comment by cdr1996** [comment]
Not a massive issue, more of a suggestion, I would say keep this open for a little while longer, maybe someone wants to work on it. Marked as low priority since its just a suggestion.

**Comment by cdr1996** [comment]
Not likely to be worked on
