### ISSUE TITLE
gm_construct_flatgrass_v6-2 (Client's map differs from the server's) 

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#288]
people say it's different than the workshop one?

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by seagullmania** [comment]
Anyone subscribed to this map will get the error
https://steamcommunity.com/sharedfiles/filedetails/?id=104468359

**Comment by PotcFdk** [comment]
Wtf, did the map author really create multiple versions with the same name? :disappointed:

**Comment by ghost** [comment]
Was this fixed?

**Comment by cdr1996** [comment]
Assumed fixed/no longer relevant. Reopen if still an issue.
