### ISSUE TITLE
Buddha glitch with coil nailgun

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#291]
If you are low on health and someone kills you with coil nailgun, you will start spawning a whole bunch of ragdolls, to the point that the server is tanking fps.

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by Etothepowerof26** [comment]
This is what Walki was talking about.

**Comment by Etothepowerof26** [comment]
https://i.imgur.com/GQPZlqe.png

**Comment by Etothepowerof26** [comment]
Also prevents you from respawning untill about 300 ragdolls have spawned or that you spammed revive

**Comment by Zeni44** [comment]
aren't those only clientside ragdolls

**Comment by Etothepowerof26** [comment]
From what it looks like, it has been fixed.

**Comment by Etothepowerof26** [comment]
After some further testing (not client side ragdolls) it has not been fixed, reopen???

The way I found out how to get out of this state is by clicking a lot to respawn until this effect stops

**Comment by Screampuff** [comment]
Should be fixed in the latest revision after I redid the pin code. comment if it's not and ill scream (and fix it again.)
