### ISSUE TITLE
can't change map if the server crashes on changelevel

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#292]
we could game.SetNextMap, but that's for fallbacks which we can't tell if the next map is going to break or not

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by ghost** [comment]
Still relevant?

**Comment by cdr1996** [comment]
Closed due to being 4 year old issue with no responses. Assumed fixed unless someone reopens and says otherwise.
