### ISSUE TITLE
lua editor auto save broke

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#293]
[Hook] Think -> "lua_editor_autosave_fave song tables" failed: lua/includes/modules/luacheck.check.lua:133: attempt to index local 'overwriting_node' (a boolean value)
stack traceback:
	lua/includes/modules/luacheck.utils.lua:186: in function '__index'
	lua/includes/modules/luacheck.check.lua:133: in function 'warn_unused_value'
	lua/includes/modules/luacheck.analyze.lua:393: in function 'check_unused_recursive_funcs'
	lua/includes/modules/luacheck.analyze.lua:417: in function 'analyze'
	lua/includes/modules/luacheck.check.lua:237: in function <lua/includes/modules/luacheck.check.lua:225>
	[C]: in function 'try'
	lua/includes/modules/luacheck.check.lua:249: in function 'get_report'
	lua/autorun/client/lua_editor.lua:367: in function 'getLuaCheckMessages'
	lua/autorun/client/lua_editor.lua:397: in function 'ValidateCode'
	lua/autorun/client/lua_editor.lua:749: in function 'func'
	lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156>
	[C]: in function 'xpcall'
	lua/includes/modules/hook.lua:213: in function <lua/includes/modules/hook.lua:194>
 and i can't do the !Lm too

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by ajloveslily14** [comment]
@SpiralP I believe was the last one to change this

**Comment by PotcFdk** [comment]
I don't think this is still relevant?
