### ISSUE TITLE
epoe.print is buggy

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#294]
when doing stuff like epoe.print(UndecorateNick(joff:Name())) it returns this:
Joff 101 158 255 255, !#4, meta ) Joff
what a shitty bug

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by bjoern90** [comment]
just found out it's the UndecorateNick() that's broken

**Comment by Myaats** [comment]
the UndecorateNick() function is behaving correctly, it is just returning multiple arguments. So please fix your buggy code.
