### ISSUE TITLE
coins on #2

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#295]
coins arent synced with server #1 and #2

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by ghost** [comment]
that is normal, each of the servers have their own databases, containing player's info about coins, playtime, etc.

that's my theory though,  I don't know how this stuff works

**Comment by bjoern90** [comment]
hm they was synced before but ok

**Comment by ajloveslily14** [comment]
I think it's because require is still broke on #2

**Comment by bjoern90** [comment]
:hype: just fixed it.. close this pplease

**Comment by danielga** [comment]
This happened because the keys that connected the servers between each other were revoked, making them unable to connect and synchronize data. New keys were created and everything's ok now.
