### ISSUE TITLE
area controller

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#296]
when you're stuck in a area you can't goto build or lobby or kys the console keeps saying
aowl: 
aowl: 
aowl: 
aowl: 
aowl: 
when trying !goto build or goto players via scoreboard

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Zeni44** [comment]
You do realise there is a anti goto option in the area controller right

**Comment by bjoern90** [comment]
yeah but what if other users wont remove it?

**Comment by ghost** [comment]
report or votekick.

**Comment by bjoern90** [comment]
well fuck you i can't votekick.

**Comment by ajloveslily14** [comment]
Sounds like a personal problem. Maybe you shouldn't have abused it.
