### ISSUE TITLE
lua/autorun/server/physics_reinit.lua:6: Tried to use a NULL entity!

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#297]
lua/autorun/server/physics_reinit.lua:6: Tried to use a NULL entity!
  1. GetPhysicsObject - [C]:-1
   2. CheckSilent - lua/autorun/server/physics_reinit.lua:6
    3. Remove - lua/autorun/server/physics_reinit.lua:46
     4. unknown - lua/weapons/weapon_coilgun.lua:368

Bug reported by '<color=50,50,50>Uniworst' (STEAM_0:1:62957165).

**Comment by ajloveslily14** [comment]
this is part of #291
