### ISSUE TITLE
crap server crashes *nix players

### ISSUE THREAD

**Issue by propguardiandarkcide** [Metastruct/issues#300]
ya ur shit server is people using the *nix ports of gmod 
get off ur soyboy normie shit w10 and fix it losers 

btw these are the datamining addons im talking about DUMBASS

https://pastebin.com/u/HOOBWHOMSTEALSFILES

**Comment by Tenrys** [comment]
Get off your high horses nerd

**Comment by propguardiandarkcide** [comment]
nice degenerate avatar
