### ISSUE TITLE
custom emoutes

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#301]
well zeni did a temporay fix and he wanted python to fix it but he didnt do it yet https://i.imgur.com/2zhwsGA.png

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Zeni44** [comment]
For more Info: 
Python made the 3dsmileys use URLImage instead of FastDL. Chathud still uses the FastDL version but they never get downloaded anymore

**Comment by bjoern90** [comment]
@Zeni44 00:23 - Python1320: sorry Bjoern90, I tried

**Comment by Techbot121** [comment]
I just "fixed" this with rev.15434
