### ISSUE TITLE
Broken Mediaplayer

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#302]
Yesterday, mediaplayer has been working properly. Now, it just doesn't want to show videos from Youtube at all. It doesn't say anything, it just says that "this browser doesn't support html5"..

Bug reported by '<hsv=[10+(20*sin(t()*12))]>Max<color=0,0,0>Spec' (STEAM_0:1:61600180).

**Comment by ghost** [comment]
MediaPlayer related, not Metastruct issue.

Create an issue here: https://github.com/samuelmaddock/gm-mediaplayer
