### ISSUE TITLE
tts statue

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#303]
pyhong fix your shit https://i.imgur.com/27Grx2a.jpg

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Etothepowerof26** [comment]
could have made this issue with a calmer approach, apparently looks like the dog's text-to-speach has html parsing error or something.

**Comment by ajloveslily14** [comment]
The TTS lines it grabs are from a website that hosts a static page so the page may have 404'd

**Comment by ajloveslily14** [comment]
I can't reproduce so it's either fixed or something on your end
