### ISSUE TITLE
Friendy Achievement Gift cannot be spawned in lobby

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#304]
idk why, it should be whitelisted

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by ajloveslily14** [comment]
Weird, according to sv_lobby.lua in logistics it is whitelisted, maybe it needs to have islobbyok set onto it when it spawns

**Comment by KabusDev** [comment]
I blame failcake with his billions of lua triggers for m3

**Comment by PotcFdk** [comment]
This is fixed.
