### ISSUE TITLE
banned people can still use televators / pm others

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#305]
will be working on it but just here to be noted

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by PotcFdk** [comment]
I don't see a problem with the televator usage personally. It's the same thing as walking around.

**Comment by Tenrys** [comment]
Yeah, PM still being allowed sounds like an oversight or a Python idea, I'll go with the latter

**Comment by ajloveslily14** [comment]
I can understand elevator usage but not the PMing, ill fix it

**Comment by ajloveslily14** [comment]
Apparently there's already a system where banned people have to be sent a pm first to actually talk to others.
