### ISSUE TITLE
color formatting glitch

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#306]
```
<color=255,0,0>test<
```
when entered in chat gets turned to
![screenshot](https://i.imgur.com/YuZYOAd.png)

Bug reported by 'Some_Beach' (STEAM_0:1:55684109).

**Comment by ajloveslily14** [comment]
added the help wanted label because i'm not experienced enough in patterns to know how to fix this

**Comment by Earu** [comment]
Fixed
