### ISSUE TITLE
Cant See the workshop for New models for outfitter

### ISSUE THREAD

**Issue by immortalslime53** [Metastruct/issues#308]
I used Outfitter Alot AND I MEAN ALOT i found it in a server that i was playing around in a server i used to play on it was called The Box its still here today but its gone But thats another Story but In that server i pres s C and i saw outfitter and i could do any playermodel that was not on the server playermodel list so i used a model from a youtuber i know Daithi de nogla and started ok and then i went further in and said i could do anything with this untill one day i wanted a new model but the page was not showing up if i could get some tips that would be great! i play Meta Struct server 1 but it got too out of hand i was put in to a Jail in build for a stupid reason messing with pac3 with a sans model that you could use gaster Blaster (bad idea because it could crash a person's game)

**Comment by immortalslime53** [comment]
when i said its here today but its gone THATS A TYPO!!!

**Comment by homonovus** [comment]
in short, he cant see the workshop page from lua web browser

**Comment by Python1320** [comment]
use !outfitter command with a number after which you can find from the workshop
