### ISSUE TITLE
Sliders - Physics Crash

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#31]
Trying to create a triangle with sliders between each of the (frozen) props and then attempting to individually unfreeze two of the corners with the physgun causes a physics crash.

Steps:
1. Create a plate
2. Create a second plate
   3 Center the face of one plate to the face of the other plate, wither with the Precision tool or Precision Alignment tool.
3. Offset the second plate from the first by some accessible distance (in this case 20,000)
4. Create two more plates, and use Precision Alignment to center them on opposite edge midpoints on the second plate.
5. Create sliders between the first and third, and first and fourth plates.
6. Attempt to unfreeze the third and fourth plates individually with the physgun.
7. Expect a physics crash.

Bug reported by '<color=0,200,255>Bio' (STEAM_0:1:63054980).

**Comment by ajloveslily14** [comment]
can't reproduce, assuming fixed
