### ISSUE TITLE
ERR: Couldn't include file 'tod\snow.lua' (File not found) (@lua/autorun/tod.lua (line 1001))

### ISSUE THREAD

**Issue by Etothepowerof26** [Metastruct/issues#311]
```lua
		include("tod/snow.lua")
		if SERVER then
			AddCSLuaFile("tod/snow.lua")
		end
```

should it AddCSLuaFile first?

**Comment by Myaats** [comment]
Thats server side, so it should not matter that it's included first. It's probably due to the file actually missing

**Comment by Zeni44** [comment]
The file isn't missing nor does it need to call AddCSLuaFile first.
The server hasn't restarted yet (or didn't rerun autorun/tod.lua) since it turned December and didn't call AddCSLuaFile on tod/snow.lua. It only checks for date on startup.

**Comment by Etothepowerof26** [comment]
ahh ok thanks
