### ISSUE TITLE
lua/autorun/server/engine_protects.lua:36: bad argument #1 to 'find' (string expected, got table)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#314]
1. find - [C]:-1
   2. SetModel - lua/autorun/server/engine_protects.lua:36
    3. MakeConveyor - lua/weapons/gmod_tool/stools/conveyor.lua:277
     4. RightClick - lua/weapons/gmod_tool/stools/conveyor.lua:123
      5. unknown - gamemodes/sandbox_modded/entities/weapons/gmod_tool/shared.lua:273

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by Techbot121** [comment]
should be fixed with srvaddons@cd57bdb
