### ISSUE TITLE
right clicking somebody's profile picture on the scoreboard causes a error

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#316]
[ERROR] lua/helpers/steamid_helpers.lua:49: attempt to call field 'Add' (a nil value)

Bug reported by 'loser' (STEAM_0:1:104332977).

**Comment by jule14** [comment]
yes

**Comment by Etothepowerof26** [comment]
can't reproduce, apparently said only happened on one person and that was a couple days ago

**Comment by PotcFdk** [comment]
Re-open if it happens again.

**Comment by Zeni44** [comment]
This is now fixed
