### ISSUE TITLE
cs command errors if you are using newchatsounds

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#317]
[Hook] ChatCommand -> "copysound" failed: lua/autorun/client/chat_commands_cl_cmds.lua:352: attempt to index global 'chatsounds' (a nil value)

Bug reported by 'loser' (STEAM_0:1:104332977).

**Comment by Techbot121** [comment]
yea old chatsounds got removed now this doesn't work for obvious reasons

**Comment by TW1STaL1CKY** [comment]
!cs command now works with newchatsounds (and still works for oldchatsounds).
