### ISSUE TITLE
Fishingmod format error

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#32]
[Cmd] 'fishing_mod_request_init' failed for Player [6][Michael Freedom]: lua/fishing_mod/sv_player_stats.lua:97: attempt to concatenate local 'version' (a nil value)
stack traceback:
	lua/fishing_mod/sv_player_stats.lua:97: in function 'LoadPlayerInfo'

Bug reported by 'Python1320' (STEAM_0:0:13073749).

**Comment by Python1320** [comment]
Basically the file was empty, no idea why.
