### ISSUE TITLE
nametags: AFK check disobeys cl_nametags_drawlocalplayer

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#320]
Nametags will draw on the local player if they are AFK reguardless of cl_nametags_drawlocalplayer's value.

**Comment by ajloveslily14** [comment]
I mean technically you're supposed to be away when you're afk so

**Comment by TW1STaL1CKY** [comment]
Fixed - for some reason it was checking if you had cl_nametags_drawlocalplayer on **OR** if you were AFK. Took out the AFK check because why
