### ISSUE TITLE
Chatsounds don't work

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#321]
Autocomplete works but I can't hear the sounds. Hopefully relevant convars:

```
"chatsounds_enabled" = "1"
 client server_can_execute lua_clie] chatsounds_enabled_new 

"chatsounds_enabled_new" = "1"
 client server_can_execute lua_client
 - 		0: don't autoload
		1: load only if old-chatsounds isn't loaded
		2: always load
```
	

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by PotcFdk** [comment]
Pinging relevant people: @Python1320 @Zeni44

**Comment by Etothepowerof26** [comment]
autocomplete doesnt work for me and i cant hear sounds, goluwa doesnt even download the chatsounds from their repositories

**Comment by Etothepowerof26** [comment]
nevermind, got it working. something is wierd though as it hasnt been working until i just tried when seeing this

edit: yeah cant hear sounds

**Comment by SpiralP** [comment]
you can get more info in console by using `!newchatsounds debug`

**Comment by cdr1996** [comment]
Still relevant?

**Comment by cdr1996** [comment]
Chatsounds has recently had an overhaul from my understanding. Unlikely to still be relevant. Please reopen if needed.
