### ISSUE TITLE
tod: allow loading/unloading of snow whenever

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#324]
probably would go against choices made forever ago but it'd be nice to be able to load in snow outside of snowy months (dec-feb) and unload it (ex: dont like snow at all during snowy months or only temporarily want to use snow for a screenshot or something)

**Comment by ajloveslily14** [comment]
Currently the only things server side are the ice over the little river and the footstep sounds(oddly enough) otherwise tod.RestoreAllTextures() will restore the grass and hook.Remove("Think","tod_snow") will remove the snow particles

**Comment by bjoern90** [comment]
and is the sound serverside? i saw you did some tests with the walk sound

**Comment by ajloveslily14** [comment]
Thanks to github mobile you had 3 different chances to read that I said the footstep sound is server side

**Comment by bjoern90** [comment]
oops i was too fast .-.

**Comment by bjoern90** [comment]
ok i was too fast reader

**Comment by Cynosphere** [comment]
i bet most people could care less about the ice and make their own thing out of props

as far as footsteps go, i guess just nwvars

**Comment by ajloveslily14** [comment]
added a 'tod_removesnow' console command to remove the snow materials, snow particles, and snow footstep sounds.
