### ISSUE TITLE
[NET] starfall_processor_destroy: lua/starfall/instance.lua:327: attempt to index a nil value

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#325]
[NET] starfall_processor_destroy: lua/starfall/instance.lua:327: attempt to index a nil value
stack traceback:
	lua/starfall/instance.lua:327: in function 'deinitialize'
	lua/entities/starfall_processor/shared.lua:73: in function 'Destroy'
	lua/entities/starfall_processor/cl_init.lua:100: in function <lua/entities/starfall_processor/cl_init.lua:97>
	[C]: in function 'xpcall'
	lua/includes/extensions/net.lua:84: in function <lua/includes/extensions/net.lua:56>
lua/starfall/instance.lua:327: attempt to index a nil value
stack traceback:
	lua/starfall/instance.lua:327: in function 'deinitialize'
	lua/entities/starfall_processor/shared.lua:73: in function 'Destroy'
	lua/entities/starfall_processor/shared.lua:23: in function 'Compile'
	lua/entities/starfall_processor/shared.lua:91: in function 'SetupFiles'
	lua/entities/starfall_processor/cl_init.lua:63: in function 'callback'
	lua/starfall/transfer.lua:23: in function <lua/starfall/transfer.lua:16>
	[C]: in functio

i think there was a issue for this before that was closed, too lazy to comment on it
also
traceback isnt in its entirety and i dont know why

Bug reported by 'loser' (STEAM_0:1:104332977).

**Comment by ajloveslily14** [comment]
I'm not sure if it's our code that's doing this or if it's theirs, theres been quite a few starfall updates since then so maybe it's been fixed. I'll see if it continues, another issue is it's so damn inconsistant when it happens

**Comment by Earu** [comment]
Fixed by now
