### ISSUE TITLE
saysound command does not network to other players

### ISSUE THREAD

**Issue by TW1STaL1CKY** [Metastruct/issues#326]
'saysound' for newchatsounds plays chatsounds for the localplayer only, because of the way newchatsounds works.

Currently, chatsounds from other players are triggered via the clientside OnPlayerChat hook, which in the end calls **goluwa.env.chatsounds.Say** (from a local function player_say). Saysound is a clientside command, so running it will do the same as the OnPlayerChat hook but only for yourself (since it does not network anything).

@Zeni44 - if you want to help with this

**Comment by Zeni44** [comment]
Fixed with [ed975da9e7f67702546e97eb753e64df47c93703](https://github.com/Metastruct/notagain/commit/ed975da9e7f67702546e97eb753e64df47c93703)
