### ISSUE TITLE
[ERROR] lua/helpers/puke_effect.lua:71: attempt to index field 'emitter' (a nil value)

### ISSUE THREAD

**Issue by ghost** [Metastruct/issues#328]
after drinking pure sulnalus
[ERROR] lua/helpers/puke_effect.lua:71: attempt to index field 'emitter' (a nil value)
  1. unknown - lua/helpers/puke_effect.lua:71

**Comment by Python1320** [comment]
fixed?

**Comment by ghost** [comment]
doesn't seem to happen anymore, probably fixed
