### ISSUE TITLE
mining ores

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#329]
you guys need to add blocks to prevent players picking up the ores and finding minging rocks like you did with the coins

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by ajloveslily14** [comment]
We're slowly finding and patching things. I recommend getting an ore magnet if people are stealing ore you've mined.

**Comment by TW1STaL1CKY** [comment]
There is a grace period now where for 8 seconds, only the miner of the rock can pick up the produced ore. After the 8 seconds, any one can pick it up. Also, players cannot pick up ores while in vehicles anymore.
