### ISSUE TITLE
npc miner

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#330]
players cant sell ores to the miner anymore

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by TW1STaL1CKY** [comment]
Will look into this when I get the chance.

**Comment by TW1STaL1CKY** [comment]
Bjoern says it's working again. Just tested and it is working without any changes (from me, at least).

**Comment by ajloveslily14** [comment]
Yeah idk what the issue was but just refreshlua fixed it, maybe a hook error or something

**Comment by TW1STaL1CKY** [comment]
Most likely
