### ISSUE TITLE
Tweak name color enforcement to be less strict.

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#331]
I don't see how C06080 (192,96,128) is visually anywhere near 180,60,180.

![C06080](https://cdn.discordapp.com/attachments/449086785239253002/539672366108901398/c06080.png) ![Dev team color](https://cdn.discordapp.com/attachments/449086785239253002/539677932742770699/b43cb4.png)

**Comment by Earu** [comment]
Name enforcement doesnt exist anymore
