### ISSUE TITLE
ctp and pac bad render hook restoring

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#332]
ctp and pac dont restore some rendering hooks or restore them wrong, to test: hook.Add("renderhook",weapon,weapon.Function)

Bug reported by '<color=244, 66, 110>Earu Arcana' (STEAM_0:0:80006525).

**Comment by Zeni44** [comment]
)))))))))))

**Comment by Myaats** [comment]
(((((((((((

**Comment by Earu** [comment]
https://i.imgur.com/1pkhxCW.jpg
without ctp -> works fine
goes in ctp -> works fine
goes back to first person -> bug

Same with pac editor cam

**Comment by CapsAdmin** [comment]
My guess is that you're using Eye/Pos/Angles/Dir outside of a render function which causes undefined behavior.

**Comment by cdr1996** [comment]
Visual bug, marking as low priority. Also not sure if fixed?

**Comment by cdr1996** [comment]
@Earu

**Comment by Earu** [comment]
I think it still happens but its annoying because its typically two addons that dont respect each others.
@CapsAdmin

**Comment by cdr1996** [comment]
Sadly a stale issue, reopen if needed.
