### ISSUE TITLE
Proxy Discord emotes

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#335]
`[DiscordEmoticons] Http fetch failed for	https://cdn.discordapp.com/emojis/536265505649197066.png	: 403`

[Discord changed something on Cloudflare that broke both Awesomium and Chromium on GMod from making requests and are acting dumbfucked about it as always.](https://github.com/discordapp/discord-api-docs/issues/849) The only way I can think to get around this is proxying the URLs.

**Comment by Python1320** [comment]
Correction: It is using valve's http client and not chrome tech at all.

```http
>nc -l -p 1234
GET / HTTP/1.1
User-Agent: Valve/Steam HTTP Client 1.0 (4000)
Host: 127.0.0.1:1234
Accept: text/html,*/*;q=0.9
Accept-Encoding: gzip,identity,*;q=0
Accept-Charset: ISO-8859-1,utf-8,*;q=0.7
```

**Comment by Python1320** [comment]
Yeah it's specifically 4000, 4001 works fine etc

**Comment by Cynosphere** [comment]
Closing as fixed

instead of proxying, emotes were switched to use `media.discordapp.net`
