### ISSUE TITLE
20thcenturyfox is played as "2"

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#337]
20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"20thcenturyfox is played as "2"

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by Python1320** [comment]
WontFix

**Comment by PotcFdk** [comment]
@Python1320 why not?

**Comment by Python1320** [comment]
So this is an actual issue? Shorter chatsounds overriding longer ones?

**Comment by PotcFdk** [comment]
Not overriding, it sounds more like a parser issue that it doesn't recognize the entire words correctly and instead matches based on a partial string (e.g. "2" instead of "20thcenturyfox").

**Comment by ZehMatt** [comment]
How are words currently separated? There has to be some delimiter

**Comment by PotcFdk** [comment]
@ZehMatt I think it's gotta be [`chatsounds.GetScriptFromText`](https://github.com/Metastruct/garrysmod-chatsounds/blob/master/lua/chatsounds/cl_core.lua#L1029) (called [here](https://github.com/Metastruct/garrysmod-chatsounds/blob/master/lua/chatsounds/cl_core.lua#L1203))

**Comment by Python1320** [comment]
https://gitlab.com/CapsAdmin/goluwa/blob/master/game/lua/libraries/audio/chatsounds/chatsounds.lua#L245

**Comment by Earu** [comment]
This is not relevant to metastruct issues but to the now standalone chatsounds that @CapsAdmin is maintaining.
