### ISSUE TITLE
Player position failure on vehicle seats

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#338]
Meta Construct's server problem only:
- player position on seats changes "mysteriously" while driving.

Bug reported by '<c=0064ff>Actros' (STEAM_0:0:480358881).

**Comment by bjoern90** [comment]
here's a picture https://i.imgur.com/rObL52P.jpg

**Comment by ZehMatt** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3765
