### ISSUE TITLE
msitems equip console command

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#340]
whenever i do that command i can wear a fuck ton of it and i cant even unequip it and it even triggers the lagscore https://i.imgur.com/kIfYpGG.png (i tested with timer to make auto wear and it keeps on wearing items and wont stop )

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Ramalayha** [comment]
Should be fixed now.

**Comment by Ramalayha** [comment]
Should be fixed now.
