### ISSUE TITLE
error when trying to use % operator with newchatsounds

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#346]
[Hook] OnPlayerChat -> "chatsounds" failed: game/lua/libraries/audio/chatsounds/chatsounds.lua:231: invalid capture index
stack traceback:
	[C]: in function 'gsub'
	game/lua/libraries/audio/chatsounds/chatsounds.lua:231: in function 'preprocess'
	game/lua/libraries/audio/chatsounds/chatsounds.lua:556: in function 'GetScript'
	game/lua/libraries/audio/chatsounds/chatsounds.lua:891: in function 'Say'
	notagain/goluwa/autorun/client/chatsounds.lua:116: in function 'func'
	lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156>
	[C]: in function 'xpcall'
	lua/includes/modules/hook.lua:213: in function 'Call'
	lua/chatbox/transportation.lua:181: in function 'ReceiveChatMessage'
	lua/chatbox/transportation.lua:218: in function 'ReceivedData'
	lua/chatbox/transportation.lua:243: in function <lua/chatbox/transportation.lua:223>
	[C]: in function 'xpcall'
	lua/includes/extensions/net.lua:84: in function <lua/includes/extensions/net.lua:56>

its a gsub error so i guess it forgot to ?sanitize? input

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by Etothepowerof26** [comment]
heres my test:
`how could one man have slipped through your forces fingers time and time again how is it possible this is not some agent provocateur or highly trained assassin we are discussing gordon freeman is a theoretical physicist who had hardly earned the distinction of his ph d at the time of the black mesa incident i have good reason to believe that in the intervening years he was in a state that precluded further development of covert skills the man you have consistently failed to slow let alone capture is by all standards simply that an ordinary man how can you have failed to apprehend him:pitch([t()%4])`
