### ISSUE TITLE
Font bugs

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#35]
Don't tell us there's an error creating the font and just fallback
[18:06] Player [3][ZS] ERR: There was an error creating the font!

times that about 20

This person had probles with chat not updating, PAC editor not working and scoreboard text not showing

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by LUModder** [comment]
example 1:
[http://i.imgur.com/62amgTb.png]()

**Comment by Cynosphere** [comment]
No one has been able to replicate this so
