### ISSUE TITLE
HnS bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#350]
lua/hns_minigame/sv_hns.lua:134: Tried to use a NULL entity!
  1. __newindex - [C]:-1
   2. StartGame - lua/hns_minigame/sv_hns.lua:134
    3. unknown - lua/hns_minigame/sv_hns.lua:410

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by Etothepowerof26** [comment]
when a player leaves, it breaks when the game starts

**Comment by Etothepowerof26** [comment]
srvaddons@091a928 should've fixed it (I couldn't find anything nilling the player if they leave)

**Comment by Etothepowerof26** [comment]
cool
