### ISSUE TITLE
MetaWorks/Badges: Check host_timescale cvar on client before giving FPS badge

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#357]
im sorry
![](https://totallynotavir.us/i/257309cx.png)

**Comment by Cynosphere** [comment]
@PotcFdk if you want to badge ban me for this, go right ahead.

**Comment by Cynosphere** [comment]
Just to clear things up, I was not intentionally trying to break the badge and another dev has rolled the badge back already.

**Comment by PotcFdk** [comment]
Weird, I thought this was already checked in a proper way. It's not the highest priority right now, so I guess I'll just add it to my todo list and work on it later, unless somebody else fixes it first.

**Comment by ghost** [comment]
Is this still relevant? I tried to change host_timescale on my client but either get Can't use cheat cvar host_timescale in multiplayer, unless the server has sv_cheats set to 1 or Can't change replicated ConVar host_timescale from console of client, only server operator can change its value.

Tried with command .cheats 1 as well. Needs more info? Let me know if I can close this.

**Comment by cdr1996** [comment]
Cannot seem to replicate after some extensive testing. Reopen if still an issue, but otherwise this seems either fixed or cannot be reproduced.
