### ISSUE TITLE
Whitelist/blacklist for goto

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#36]
It'd be nice to have a whitelist/blacklist system of who can goto you. Yes, togglegoto exists, but it still allows people on your steam friends to goto you and it'd just be easier to impliment a list and not have togglegoto exist.

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by edunad** [comment]
I added a hook for you to allow or disallow the teleporting, that might help

**Comment by zxz41** [comment]
I know this issue is old. But I agree with having so that you can blacklist/whitelist atleast one or more people, instead of completely disabling it. Why haven't this been implemented yet?

**Comment by notcake** [comment]
We apologize for any inconvenience caused.

This is now our top priority and both the Metastruct localization and product testing teams have been reassigned to work on this.

**Comment by Cynosphere** [comment]
Do you guys not see who's assigned to this? I'll work on it in my free time

**Comment by notcake** [comment]
Flex you still haven't submitted last week's TPS reports.

**Comment by Tenrys** [comment]
I think you've had a bit of free time since then @LUModder

**Comment by ajloveslily14** [comment]
Done.
