### ISSUE TITLE
newchatsounds [webaudio] 29: The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#361]
this happens on the x86-64 branch

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by notcake** [comment]
delete chatsounds

**Comment by ghost** [comment]
Does it still happen?

**Comment by cdr1996** [comment]
I have come across this error before too, but haven't seen it in ages, if at all recently. I'm going to assume it's fixed since no one has responded. Reopen if needed.
