### ISSUE TITLE
newbies

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#365]
when a new players join for first time ( ● Joined for the first time!) server's dying for like 10 sec and cleaning up the server for no reason at all

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by ghost** [comment]
most likely a issue with the database? there have been other issues with it recently

**Comment by TW1STaL1CKY** [comment]
We're already aware. It isn't an easy fix, but I can say it is being looked into.

**Comment by bjoern90** [comment]
good

**Comment by PotcFdk** [comment]
I think this is related to the recent issues with opening files (including the SQLite database). Can anyone confirm? If yes, we can close this issue, because it's already being watched and worked on.

**Comment by ghost** [comment]
I think they somewhat fixed this, server doesn't have death lag anymore when people spawn but I probably need clarification here

**Comment by Earu** [comment]
Not sure if that specific data was switched over to postgresql, anyway its kind of a non issue now, it was only the case because #1 HDD drive was VERY slow.
