### ISSUE TITLE
error after entering zen

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#369]
[Hook] PreDrawOpaqueRenderables -> "ms_zen" failed: lua/metastruct/logics/sh_zen.lua:72: Tried to use a NULL entity!
stack traceback:
	[C]: in function 'SetModelScale'
	lua/metastruct/logics/sh_zen.lua:72: in function 'init'
	lua/metastruct/logics/sh_zen.lua:91: in function 'func'
	lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156>
	[C]: in function 'xpcall'
	lua/includes/modules/hook.lua:213: in function <lua/includes/modules/hook.lua:194>

keep in mind this may be related to the stuff I've been seeing in console along the lines of: "Couldn't make effect 'stooldecal' - Too many Lua Effects (2049)! Are you killing them properly?
Couldn't make effect 'selection_indicator2' - Too many Lua Effects (2049)! Are you killing them properly?
Couldn't make effect 'tooltracer2' - Too many Lua Effects (2049)! Are you killing them properly?
CBaseEntityList::AddNonNetworkableEntity: no free slots!
CBaseEntityList::AddNonNetworkableEntity: no free slots!
CBaseEntityList::AddNonNetworkableEntity: no free slots!

Bug reported by 'loser' (STEAM_0:1:104332977).

**Comment by cdr1996** [comment]
Anyone know if this was fixed?

**Comment by cdr1996** [comment]
Haven't seen anyone have an error like this since, and it seems the file which was producing these errors has also been changed since. Unless anyone can reproduce this I'm going to consider this no longer an issue and close it. Reopen if this resurfaces.
