### ISSUE TITLE
Weapons can be spawned in the lobby with partymode = off

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#37]
\<AvastAntiPony> [...] there is in the top a unmarked lobby field
\<AvastAntiPony> so you can spawn weapons into lobby

![screenshot](https://i.imgur.com/dqpEgeD.jpg)

**Comment by LUModder** [comment]
Can't find the file for it, but the area needs to be raised to about 16316 or higher

**Comment by PotcFdk** [comment]
We're on _151 now, has this been fixed?

**Comment by Cynosphere** [comment]
Have not tested yet

**Comment by Cynosphere** [comment]
Only works if you aim at the rounded wall while up here, anywhere in the core room wont spawn it

**Comment by ghost** [comment]
Fixed by Python1320.

**Comment by PotcFdk** [comment]
You gotta ping @Python1320 so he gets all the dingdings in his mail account. Maybe he'll remember to close the issues he fixes. :stuck_out_tongue:

**Comment by ghost** [comment]
@PotcFdk: I asked him to fix it when I posted this since he was in Hammer.
