### ISSUE TITLE
Ragdoll breaks knife

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#370]
When ragdolled and queueing for knife, you look at your target but you arent teleported to the area. 

Bug reported by '<c=ff0000>Atlas' (STEAM_0:1:156815527).

**Comment by ghost** [comment]
reserver checks if you are solid when you queue but it doesn't check when queued, this is also a issue with knife itself, if you ragdoll yourself during the game your opponent will not be able to hit you

**Comment by jule14** [comment]
The system is flawed!

**Comment by Cynosphere** [comment]
Ragdolling before queuing was fixed forever ago, ragdolling/spectating in knife I added a hook for recently

Can be closed
