### ISSUE TITLE
double posting when someone uploads an image via discord

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#372]
19:44 - [IRC] Discord: [Not Shane, kid.] 
19:44 - [IRC] Discord: https://cdn.discordapp.com/attachments/179265653864267777/558435787717345287/unknown.png
19:44 - [IRC] Discord: https://cdn.discordapp.com/attachments/179265653864267777/558435787717345287/unknown.png

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by Cynosphere** [comment]
should be put on metaluvit's issue repo and not here i think

**Comment by Etothepowerof26** [comment]
probably

**Comment by Cynosphere** [comment]
[Fixed](https://github.com/Metastruct/metaluvit/commit/2c3860c9c4e610787202825e2276ca01994b6cff), issue can be closed.
