### ISSUE TITLE
scoreboard: "Open Webchat" URL is outdated.

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#373]
still goes to metastruct.org/webchat and not www3.metastruct.net/webchat

**Comment by Myaats** [comment]
this should probably be made a redirect on the website, instead of changing the url

**Comment by Cynosphere** [comment]
we dont own metastruct.org anymore though

**Comment by Myaats** [comment]
a redirect on metastruct.net has been added, and the url should be updated from the update + next restart / map change
