### ISSUE TITLE
hax monitor spam

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#374]
i wish there's a way to mute those hax sound or make it nonspamable ...

Bug reported by '^7Bjoern90 #MaxCoinsReached' (STEAM_0:1:42844056).

**Comment by PotcFdk** [comment]
> nonspamable ...

Hax monitors are supposed to be rate-limited by requiring you to buy them, spending limited money.

**Comment by bjoern90** [comment]
but other users use em to push player away like minges (if they wont use the cursed bullet .-.) but for me the sounds are loud af

**Comment by ghost** [comment]
I've added something to stop people spamming the chat command. Any further suggestions please comment.

**Comment by ghost** [comment]
Since no replies were made since and an addition has been made, I will close this issue.
