### ISSUE TITLE
updates postes twice

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#376]
https://i.imgur.com/U6CxrYF.png just like when uploading pictures on discord

Bug reported by '^7Bjoern90 #MaxCoinsReached' (STEAM_0:1:42844056).

**Comment by Zeni44** [comment]
Can't seem to reproduce it.
This was either a rare bug that occurred or is an issue on your end as you are overwriting functions to make it print in EPOE as it's not suppose to.

Reopen on recurrence
