### ISSUE TITLE
Can't close SCAP window

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#378]
[SCAP] 	Got 56733* from <color=0,0,0><hsv=[t()*80]>Ro<color=72,72,72>Bot
[SCAP] New SCAP from <color=0,0,0><hsv=[t()*80]>Ro<color=72,72,72>Bot! ( press the 1 key to view )
[SCAP] SCAP's annoying? Type scap_disabled 1 in console or !scapblock player
[[ PM From RoBot ]]
automated	RoBot
[SCAP] 	[BASE64] Encoding... (56956)
[SCAP] 	[BASE64] Done! (75944)

[ERROR] 

Bug reported by '<c=ff0000>Atlas' (STEAM_0:1:156815527).

**Comment by Python1320** [comment]
Sending or receiving?

**Comment by ghost** [comment]
Player doesn't seem active anymore, no idea how to reproduce
