### ISSUE TITLE
[lua_screen] No ent.Draw3D2D: artboard

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#382]
`Screen error (Entity [677][lua_screen], artboard): No ent.Draw3D2D: artboard`
also this happens some time before the above:
`Player [20][PotcFdk] ERR: [Luascreen] No file: artboard`

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by ghost** [comment]
It's a Lua screen that I've created temporarily

**Comment by Myaats** [comment]
@WicopeeDot I see no reason to close the issue until it has been fixed

**Comment by ghost** [comment]
Did I mention that it was a Lua screen that I've created *temporarily*?
