### ISSUE TITLE
driveable crow

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#384]
[ERROR] lua/helpers/shd_module_multimodel.lua:184: Tried to use a NULL entity!
  1. SetModel - [C]:-1
   2. DrawChild - lua/helpers/shd_module_multimodel.lua:184
    3. DrawChild - lua/helpers/shd_module_multimodel.lua:320
     4. Draw - lua/helpers/shd_module_multimodel.lua:383
      5. unknown - lua/autorun/sent_driveable_crow.lua:525

it happens when it's being looked at

Bug reported by '^7Bjoern90 #MaxCoinsReached' (STEAM_0:1:42844056).

**Comment by ghost** [comment]
From what I can see the driveable crow has been removed so this issue could probably be closed.
