### ISSUE TITLE
chatsound.exe has stopped working

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#385]
![screenshot](https://i.imgur.com/185vsl6.png) cant restart it .-.

Bug reported by '^7Bjoern90 #MaxCoinsReached' (STEAM_0:1:42844056).

**Comment by PotcFdk** [comment]
@CapsAdmin I guess

**Comment by Techbot121** [comment]
this was already probably fixed with https://github.com/Metastruct/notagain/commit/ed569761196642203ce0ed7c337eb78bd2270623
re-open if the Issue still persists.
