### ISSUE TITLE
Add "No IRC users" to scoreboard

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#39]
As title says

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by PotcFdk** [comment]
Only @Python1320 knows how the scoreboard works.

**Comment by edunad** [comment]
I messed with the scoreboard on meta3 to add easter, its not hard, its easy to add / remove stuff

**Comment by LUModder** [comment]
Plus I've overhauled it for my old server, I guess I'll be assigned to it
