### ISSUE TITLE
hax monitor / tp spam

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#391]
players can still use/spam when dead.. maybe make a blocker to it?

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Zeni44** [comment]
"hacc screen"?

**Comment by VCSoldier** [comment]
he means the hax monitor, people can kill themself and use tp to annoy the shit out of people

**Comment by Etothepowerof26** [comment]
Hax monitors now have a delay of 25 seconds.

**Comment by PotcFdk** [comment]
I hope you mean *cooldown*.
