### ISSUE TITLE
TTS is broken

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#392]
Log:
[TTS] DOWNLOAD http://g2.metastruct.uk.to:2095/tts/ogg.lua?txt=%3Cvoice+name%3D%22Denis%22%3Etest
FAIL	 unsuccessful	 nil

Bug reported by 'djmartin779' (STEAM_0:1:103039307).

**Comment by ghost** [comment]
GMOD branch: x86-64
Server Number: #1

**Comment by Etothepowerof26** [comment]
The TTS service is hosted on the 2nd server, which is currently down.

**Comment by Etothepowerof26** [comment]
The URL for the TTS service has not been changed.

Old URL: http://g2.metastruct.uk.to:2095/tts/ogg.lua
Needed URL: http://g2.metastruct.net/tts/ogg.lua
(example: http://g2.metastruct.net/tts/ogg.lua?txt=%3Cvoice+name%3D%22klatt4%22%3Efat)

**Comment by Etothepowerof26** [comment]
It has been changed and a server rehash should fix this.
