### ISSUE TITLE
Ores out of bounds

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#395]
apparently they enjoy doing this to people while theyre mining.

![screenshot](https://i.imgur.com/3HoZ9NU.png)

Bug reported by '(lightly)<color=255,255,255>Salted<color=255,0,0>Wolfenstein3D' (STEAM_0:0:183298430).

**Comment by ghost** [comment]
As far as we know this is fixed as of lately, if you encounter any more problems please do inform us.
