### ISSUE TITLE
Gold bars and the RP/DM area

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#397]
A few people have started using the gold bar's "Bask in it's Glory" interaction to gain up to 150HP mid-combat, and even heal without spending Medkit ammo or coin-purchased health vials & kits.

Armor hacks are consumable, and go up to 250, but Health shouldn't be this way.

this is basically free health + an overheal that's semi-permanent.

it's also shit when combined with a jetpack or propeller engine, since The now-flying player has 250 health, 250 armor, and possibly a Team-chat Lua script for a crappy aimbot. and yet i've done this garbage before in all honesty.

It just breaks things in twelve whole pieces...

Bug reported by '<color=150,0,150>Emb<color=0,225,139>er<hsv=[t()*75]>Heart' (STEAM_0:0:183298430).

**Comment by bjoern90** [comment]
so? why do you even play meta when you hate those stuffs? we cant limt everything on that area!

**Comment by Etothepowerof26** [comment]
Stop being toxic, its just an oversight

**Comment by Etothepowerof26** [comment]
Should we limit health, and armor in roleplay area?

**Comment by bjoern90** [comment]
even you cant spawn medkit and armors? medkit as a weapon has limit "ammos" and recharing slowly

**Comment by ghost** [comment]
Players entering RP will now have HP reset to 100 and you can no longer use gold bar bask function in RP.
