### ISSUE TITLE
[notagain/newchatsounds] Add saysound networking to newchatsounds repo

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#399]
(I'd report this on the notagain fork if issues were enabled)

It'd be nice to have the networking used for saysound with the repo instead of it being missing and proprietary to only Meta, where people have to add their own handler for it.

**Comment by Tenrys** [comment]
report it to the og repo?

**Comment by Zeni44** [comment]
Why not post this on the official notagain repo where it's forked from

**Comment by Cynosphere** [comment]
Networking of saysound doesn't even exist in the original repo, I might make an issue there also for it maybe.

**Comment by Tenrys** [comment]
Just merge it in a fork and make a pull request 4head

**Comment by PotcFdk** [comment]
I don't even know what this is about, should this be closed?

**Comment by Zeni44** [comment]
https://github.com/PAC3-Server/notagain/issues/152

This can be closed for now as it's kinda unrelated to us as we have it and we don't control the official repo.
See referenced issue for progress on this.

Feel free to merge our changes in a fork that adds this behavior and make a pull request to the official repo.
