### ISSUE TITLE
Errors w/ tf2 weapons...even though I own TF2

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#4]
Exactly what the description says. I see giant ERRORs on the TF2 SWEPs, even though I own TF2.

Bug reported by 'PatMartins |G4P| #Doom4Hype' (STEAM_0:1:10764898).

**Comment by notcake** [comment]
Have you tried validating your TF2 cache?
Also screenshot the checkbox menu of games to mount in the Garry's Mod menu for us.

**Comment by Python1320** [comment]
Validate TF2
