### ISSUE TITLE
IRC relay doesn't properly ignore other server's message if they include underscores

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#402]
Shown with meta 2, which joined with 2 underscores in its nick

```12:48 - [IRC] meta2__: <color=170,0,0>#2 <color=0,204,0>▸ <color=0,0,204>vaperror <color=153,153,153>( STEAM_0:1:100369329 ) has spawned```

```12:48 - [IRC] meta2__: <color=170,0,0>#2 <color=0,0,204>● Last seen <color=0,0,255>on 07/18/19 at <color=0,204,0>21:01. <color=153,153,153>(11 d, 19:47:39 ago)```

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by Etothepowerof26** [comment]
Okay, formatting issues

There we go.

**Comment by Etothepowerof26** [comment]
Just changed the server's nick back to "meta2", but probably should add a nickname check

**Comment by PotcFdk** [comment]
The relays shouldn't ever end up with their alternative `meta?_` and `meta?__` names but instead kill the user that is currently holding `meta?`. This seems to have failed here.
I just fixed a rare Lua error that I believe is the root cause for this behavior, so this shouldn't happen again.
