### ISSUE TITLE
Variable "depth" doesn't exist after commit 8f52900d542c01e6cff08fdaa77e2fc00e2bd175

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#404]
Player [4][Daedliy] ERR: [Hook] PostDrawTranslucentRenderables -> "nametags" failed: lua/fast_addons/nametags.lua:75: attempt to perform arithmetic on global 'depth' (a nil value)
Player [4][Daedliy] ERR: stack traceback:
Player [4][Daedliy] ERR: 	lua/fast_addons/nametags.lua:75: in function 'DrawNameTagText'
Player [4][Daedliy] ERR: 	lua/fast_addons/nametags.lua:236: in function 'func'
Player [4][Daedliy] ERR: 	lua/includes/modules/hook.lua:171: in function <lua/includes/modules/hook.lua:156

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by PotcFdk** [comment]
@notcake

**Comment by notcake** [comment]
@Python1320

**Comment by Etothepowerof26** [comment]
It has been yeeted/yote/insert past tense of "yeet"
