### ISSUE TITLE
Demoman: Z-fighting

### ISSUE THREAD

**Issue by PotcFdk** [Metastruct/issues#405]
![screenshot](https://cdn.discordapp.com/attachments/164735698589450241/606177729657700382/unknown.png)
![screenshot](https://cdn.discordapp.com/attachments/164735698589450241/606177888412237844/unknown.png)
According to @Python1320 this is caused by some nVidia quirk on older cards.
Can be mitigated by moving the lua_screen one Vector unit away from the wall.
How do we deal with that?

**Comment by Etothepowerof26** [comment]
Could move the luascreen by its position plus its forward vector.

**Comment by Python1320** [comment]
is moved one unit away
