### ISSUE TITLE
msreporter has invalid body when sending + physgun chain achievement suggestion

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#406]
[Aowl] Player [13][SpiralP] command eprof took 438 ms
[NET msreporter] Player [13][SpiralP]: lua/autorun/server/msreporter.lua:94: Body is invalid!
stack traceback:

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by PotcFdk** [comment]
@SpiralP 
1. Can you explain the idea more? What does physgunnning people in a circle mean, and what does _more people_ mean in this context?
2. How did you trigger the bug?

**Comment by Etothepowerof26** [comment]
For the ms-reporter error, he tried to use an empty body, mentioned in #409. 

For "physgunning people in a circle", it just means creating a grab chain, by grab I mean picking up people with the physics gun.
Here's an example with 3 people: you, player 1, player 2
- You grab player 1.
- Player 1 grabs player 2.
- Player 2 grabs you.

More people in that context means:
- You grab other player.
- The other player grabs another player.
- The player that was grabbed by the other player grabs another player.
- This goes on until the last player in this sequence grabs you.

The grab chain length is `amount of people - 1`. In this case, a badge of level 2 would mean that you and 2 other people formed a successful grab chain.

Successful grab chain just means that the link is closed. If you grab someone else and they don't grab anyone (they cannot grab you) then the grab chain length is 0.

Here is some code I made a week ago, around the time when this "issue" was created:
```lua
_R.Player.GetGrabChain = function(self)
	local i = 0
	local grabee = self
	while true do
		if not grabee.physgunpickedup then -- we're not picking up anyone, or the player that is being grabbed isn't picking up anyone
			i = 0
			break
		end
		
		if grabee.physgunpickedup == self then -- the player is grabbing us, break the loop
			break	
		end
		
		-- store the grabbed person in this variable, increment chain counter
		grabee = grabee.physgunpickedup
		i = i + 1
	end
	
	return i
end
```

**Comment by cdr1996** [comment]
This is kinda an issue and a suggestion in one thing. I don't know if anyone wants to work on the physgunning achievement, so if someone does maybe comment here, since this issues pretty old.

As for the msreporter thing I don't know if this has been fixed since or if its still relevant.

**Comment by Etothepowerof26** [comment]
If I recall correctly the msreporter bug was fixed a little bit after this
issue was posted. Probably not though.

As for the physgun suggestion, I wouldve loved to work on it, but I can't
really test the badge out because I'm banned from the Metaworks achievement
system, still. Thats probably why this suggestion fell off. Still a funny
idea, though

**Comment by PotcFdk** [comment]
>  I'm banned from the Metaworks achievement system, still.

I just deactivated all remaining blacklist entries, they don't really serve any purpose anymore.

**Comment by cdr1996** [comment]
@Etothepowerof26 do you want to work on the physgun achievement thing?

**Comment by Etothepowerof26** [comment]
Yeah, I will this weekend as i was busy with school stuff.

**Comment by Zeni44** [comment]
I looked into the physgun achievement thing as I remember writing some code for it long ago but I had some issues.

Found it again, remade it and now it works. Just need to push it to the server.

**Comment by cdr1996** [comment]
Epic

**Comment by Etothepowerof26** [comment]
I also had some old code for it and I vaguely remember working on it with
you. Ill take a look at it when I get home

**Comment by cdr1996** [comment]
Okay so I guess we could call the physgun achievement done, just tested the msreporter thing and can confirm it is not fixed, trying to use an empty description will still produce this error.

**Comment by cdr1996** [comment]
Actually looking through the code, this looks like it's working as intended since its using assert to check the length of the title and body. If we don't want it to throw an error I guess we could just not do anything or notify the client that they must provide an appropriate input, but regardless it isn't my code and I would rather not touch it especially considering it's just a minor inconvenience. I'll keep this open for now until any decision is made on the latter and we can confirm the physgun achievement code is live on the server.

**Comment by cdr1996** [comment]
Physgun achievement has been added to the server and the msreporter has invalid body when sending appears to be working as intended from what I've seen from reading the code, therefore not a bug. I guess we can now call this closed.
