### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#409]
1. You can hax while dead and still kill people
2. With no description, the msreporter errors:
[NET msreporter] Player [24][twentysix]: lua/autorun/server/msreporter.lua:94: Body is invalid!
stack traceback:
	[C]: in function 'assert'
	lua/autorun/server/msreporter.lua:94: in function <lua/autorun/server/msreporter.lua:81>
	[C]: in function 'xpcall'
	lua/includes/extensions/net.lua:84: in function <lua/includes/extensions/net.lua:56>

Bug reported by '¯\_(ツ)_/¯' (STEAM_0:0:70542806).

**Comment by Etothepowerof26** [comment]
Bug 2 is intended, sorry
