### ISSUE TITLE
Fonts in name with blacklist

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#41]
Bring back font markup in names but blacklist big fonts

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by PotcFdk** [comment]
I'm against this proposal.

**Comment by danielga** [comment]
I don't see the point in allowing tiny or Comic Sans names.
So, that's a no from me.

**Comment by edunad** [comment]
Meh, i don't mind

**Comment by Cynosphere** [comment]
I guess this isn't being added
