### ISSUE TITLE
notagain/goluwa/libraries/client/common_audio.lua:18: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#411]
[ERROR] notagain/goluwa/libraries/client/common_audio.lua:18: bad argument #1 to 'ipairs' (table expected, got nil)
  1. Compile - lua/starfall/instance.lua:99
   2. Compile - lua/entities/starfall_processor/shared.lua:28
    3. SetupFiles - lua/entities/starfall_processor/shared.lua:85
     4. callback - lua/entities/starfall_processor/cl_init.lua:63
      5. unknown - lua/starfall/transfer.lua:23
       6. xpcall - [C]:-1
        7. Remove - lua/starfall/netstream.lua:52
         8. Read - lua/starfall/netstream.lua:37
          9. unknown - lua/starfall/netstream.lua:290
           10. xpcall - [C]:-1
            11. unknown - lua/includes/extensions/net.lua:84

Bug reported by '<color=143,0,0>Crabby<color=255,94,94>Stork' (STEAM_0:0:54038091).

**Comment by PotcFdk** [comment]
Is this a [notagain](https://github.com/PAC3-Server/notagain) upstream bug?

**Comment by MeteorTheLizard** [comment]
Issue was recently fixed. [Metastruct/notagain@85b5895](https://github.com/Metastruct/notagain/commit/85b58952adf2d69617a2da3aaccd656da5de80f8)

**Comment by PotcFdk** [comment]
Upstream issue https://github.com/PAC3-Server/notagain/pull/153
