### ISSUE TITLE
RP Weapons

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#413]
You can use lite_flashbang and lite_smokegrande weapons outside of rp. Look below for reproducing
Reproduction:
* Enter RP Zone
* Get either the lite Flashbang or Smokegrenade.
* (Optional) Get a bit of ammo of it.
* Exit RP Zone

And now you can throw the nades (which of course will get you votekicked for annoying ppl)
plez fix

Bug reported by 'zynx' (STEAM_0:1:78019534).

**Comment by Zeni44** [comment]
fixed
