### ISSUE TITLE
Decompress LZMA Decompress cache/workshop/946218833878996255.cache oversized file

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#414]
coDecompress LZMA Decompress cache/workshop/946218833878996255.cache oversized file
NeedWS 1380223612 fail decompress

Bug reported by '<color=143,0,0>Crabby<color=255,94,94>Stork' (STEAM_0:0:54038091).

**Comment by Etothepowerof26** [comment]
It says the error. The model that someone was trying to request is larger than the limit set on your client. To change this, open the Outfitter UI, click on the settings tab, and change the maximum download size to a larger value. It should also output the outfit size in chat somewhere.
