### ISSUE TITLE
notagain/goluwa/libraries/client/common_audio.lua:18: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#415]
[ERROR] notagain/goluwa/libraries/client/common_audio.lua:18: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. ExecuteEventQueue - notagain/goluwa/libraries/client/common_audio.lua:18
    3. SetSoundObject - notagain/goluwa/libraries/client/common_audio.lua:26
     4. OnLoad - notagain/goluwa/libraries/client/common_audio.lua:262
      5. HandleLoadedBrowserMessage - notagain/essential/libraries/client/webaudio.lua:1014
       6. HandleBrowserMessage - notagain/essential/libraries/client/webaudio.lua:727
        7. unknown - notagain/essential/libraries/client/webaudio.lua:195

Bug reported by '<color=143,0,0>Crabby<color=255,94,94>Stork' (STEAM_0:0:54038091).

**Comment by Etothepowerof26** [comment]
Duplicate of https://github.com/Metastruct/issues/issues/411

**Comment by Etothepowerof26** [comment]
I don't even know anymore please help me

**Comment by PotcFdk** [comment]
Duplicate of #411

**Comment by Etothepowerof26** [comment]
thanks
