### ISSUE TITLE
ftask

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#417]
make i non spammable like this shit https://i.imgur.com/d9aFTzW.png

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Zeni44** [comment]
Fixed sometime ago

**Comment by PotcFdk** [comment]
What is that fake achievement? :thinking:

**Comment by Zeni44** [comment]
yes

**Comment by PotcFdk** [comment]
"What" 
"yes"

**Comment by Zeni44** [comment]
Incase you missed out since 2018

Revision: 77bf8e2e3b91402bdca5c091370acf6fdad9b57d
Date: 20/06/2018 22:11:15
Message:
ftask, for faking achievements in the chat
