### ISSUE TITLE
When using media player sometimes the screen clicker appears and cannot be removed

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#418]
Interact with a media player and sometimes your cursor will be stuck on the screen and your movement locked. Tried disabling using gui.EnableScreenClicker( false ) but to no avail.

Bug reported by 'Carlos' (STEAM_0:0:51074124).

**Comment by ghost** [comment]
Mysteriously doesn't seem to happen anymore so I guess you could close this.
