### ISSUE TITLE
Multi-UnParent Tool can't select Parented props

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#419]
Exactly what the Title says. The Multi-UnParent tool cannot select parented props which makes this tool useless. I have to use E2 to break parents which is quite annoying. This issue only seems to exist on Meta since the workshop version works perfectly fine in Singleplayer.

Bug reported by '<c=0a0000>M<c=5c0000>eteor<c=fff>' (STEAM_0:0:41001543).

**Comment by Zeni44** [comment]
Updated to latest, tried it and it works
