### ISSUE TITLE
some bug when #2 is ded

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#42]
idfk if i told it before... fix the fucking bug!

[ERROR] lua/autorun/client/ircrelay-external-metastruct-scoreboard-crosschat.lua:45: attempt to index a nil value
  1. deluser - lua/autorun/client/ircrelay-external-metastruct-scoreboard-crosschat.lua:45
   2. func - lua/autorun/client/ircrelay-external-metastruct-scoreboard-crosschat.lua:63
    3. unknown - lua/includes/extensions/net.lua:58

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by PotcFdk** [comment]
Should be fixed, please tell me if it happens again.
