### ISSUE TITLE
Starfall coins hook is broken

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#420]
You can't use requestCoins on Entity(1) (The first player or _1) without breaking literally everything.

I don't know the source behind it but my guess is that the requestCoins function simply does not work with Entity(1) but still does all the other stuff such as running the coins hook and therefor causing certain scripts to get stuck.

Bug reported by '<c=0a0000>M<c=5c0000>eteor<c=fff>' (STEAM_0:0:41001543).

**Comment by Zeni44** [comment]
Tried it and it works just fine.
