### ISSUE TITLE
Cursed bullets problem

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#422]
Cursed bullets work on yourself. When you have them equipped and take fall damage, you literally send yourself to hell. :facepalm:

Bug reported by '<c=0a0000>M<c=5c0000>eteor<c=fff>' (STEAM_0:0:41001543).

**Comment by Python1320** [comment]
It's a feature that they work on yourself. Fall damage is an edge case that I could probably remove.

**Comment by MeteorTheLizard** [comment]
> 
> 
> It's a feature that they work on yourself. Fall damage is an edge case that I could probably remove.

doit

**Comment by Earu** [comment]
@Python1320 remove fall dmg plz

**Comment by Earu** [comment]
Fall damage were fixed
