### ISSUE TITLE
Clipping breaks custom models

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#424]
Making a halloween pac, involves witchhat and a dog head, trying to clip dog ears causes clip to break and clip entire model even if its not positioned to clip the model at all, please fix i need to make epic spooktober pacs 

The wolf head is a custom model btw

Bug reported by '<color=150,0,0>V.C.Soldier' (STEAM_0:1:429481080).

**Comment by ghost** [comment]
Can you give us some examples of this happening so we know where to start? If that's possible. Thanks.

**Comment by ghost** [comment]
I've been informed there is not much we can do on our end. Apologies. This is labelled as an upstream issue. This is something you probably want to mention in pac-issues. You can report relevant issues here. See the posted link:

https://github.com/capsadmin/pac3/issues

**Comment by PotcFdk** [comment]
Tracked here I suppose https://github.com/CapsAdmin/pac3/issues/835
