### ISSUE TITLE
Physgun ragdoll friends bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#427]
Recently being physgunned by your friends turns you into a ragdoll and 99% of the time doesn't turn you back into your normal model (I think that was the idea behind the addition?). You remain as a ragdoll and there is no way to fix it apart from rejoining the server. physgun_dont_touch_me 1 also doesn't seem to help.

Bug reported by 'Carlos' (STEAM_0:0:51074124).

**Comment by Earu** [comment]
Not part of the meta source code yet, its still WIP bugs are expected.
