### ISSUE TITLE
Chatsound abuse with the = modifier is crashing/timing out clients

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#428]
Using the = modifier in a chatsound can crash people if used in a certain way. Is there maybe a way we can nerf this or put in some protection?

Example: chatsoundname=0.000001*9999

Bug reported by '<color=0, 139, 139>Carl' (STEAM_0:0:51074124).

**Comment by DjMartin779** [comment]
whats a woman

**Comment by Python1320** [comment]
Confirmed still effective, not re-enabling chatsounds until fixed.

**Comment by Tenrys** [comment]
This is probably because goluwa is simply spawning too many audio sources at once. Would limiting the amount be sufficient maybe?

**Comment by Earu** [comment]
Caps fixed
