### ISSUE TITLE
spawning more then one firework inside eachother causes crazy physics

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#429]
spawning more then one firework inside eachother causes crazy physics

Bug reported by '<color=255,20,147>HaleyLovesRoses' (STEAM_0:0:242068064).

**Comment by ghost** [comment]
lol

**Comment by ghost** [comment]
why spawn it inside each other in the first place? it's penetrating entities
in other words, this issue can be described with `water is wet`.
