### ISSUE TITLE
Potential Dimensions Bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#430]
So, when I was playing around, I entered these kind of dimensions you can enter around lobby.. basically you come next to door and press E and it teleports you to some other place. I noticed that if you spawn something and you leave the dimension using the door and then you come back, the prop wont be owned by you so that means somebody can easily spawn like 500 props there, then just leave the area and no one can see the lags are caused by him.. or imagine something more crazier that that, it was just example..

So, I recommend to check it out.

Marcuko

Bug reported by 'Marcuko' (STEAM_0:1:61719622).

**Comment by Earu** [comment]
That was fixed
