### ISSUE TITLE
Earu's Big ass script

### ISSUE THREAD

**Issue by Marcuko** [Metastruct/issues#431]
I noticed something.. when you hit earu, u get killed.. But what if you spawn a lot of turrets and try to kill earu with them? basically, u will rape server performance with his own script xd

**Comment by Zeni44** [comment]
![fatrisitas](https://user-images.githubusercontent.com/11852198/69825819-dfb24380-1210-11ea-8f92-d46cc1d55e84.png)

**Comment by Earu** [comment]
ok boomer
