### ISSUE TITLE
Giving friend Coins

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#435]
I wanted to give my friend called 'Piaempi' 1T to buy Card but after he took it, it didnt count so basically we sent 1T to void.. can you give him the 1T ?

Bug reported by 'Marcuko' (STEAM_0:1:61719622).

**Comment by PotcFdk** [comment]
What do you mean by "it didn't count"? Did you trigger a bug?

**Comment by Marcuko** [comment]
i mean, I basically used dropcoins command and after he took the 1T, it didnt appear on his profile

**Comment by haleylovesroses** [comment]
Where did you drop the coins at? Were you in MSA at the time?

**Comment by ghost** [comment]
Stale issue with no comments since, going to close and anyone can reopen if this is still relevant
