### ISSUE TITLE
scoreboard issue

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#437]
[21:06] Player [16][kurpaelzer] ERR:   lua/scoreboard/modules/player_panel.lua:1671: attempt to concatenate a nil value
  1. f -   lua/scoreboard/modules/player_panel.lua:1671
   2. RefreshTags -   lua/scoreboard/modules/player_panel.lua:1869
    3. RefreshTags -   lua/scoreboard/modules/main.lua:238

Bug reported by 'Wicopee' (STEAM_0:1:62957165).

**Comment by ghost** [comment]
fixed
