### ISSUE TITLE
newchatsounds: aliases don't work anymore?

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#438]
`ayy lmao` plays, but is supposed to be aliased to `ace of base`, too:

```Lua
L["ace of base"]={{path="chatsounds/autoadd/music/ayy lmao.ogg",length=21.838}}
L["ayy lmao"]={{path="chatsounds/autoadd/music/ayy lmao.ogg",length=21.838}}
```

However only `ayy lmao` works, `ace of base` doesn't. Doesn't even show up in the autocomplete list.

Bug reported by '^3Potc :flag_de: Fdk' (STEAM_0:1:30490065).

**Comment by cdr1996** [comment]
This is still relevant, just tried and confirmed. Not sure who would be best to consult about this issue, so help wanted from anyone who knows.

**Comment by cdr1996** [comment]
No responses were received from anyone and apparently chatsounds was updated. If this is something we still need to work on please reopen because we can't do anything without further elaboration on the issue.
