### ISSUE TITLE
setting vehicle model to brush crashes server

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#439]
"setting a simfphys car to model  *123 causes it to crash the server as soon as someone enters it."
found by JOKER (STEAM_0:1:26354828 )

Bug reported by '<c=3300dd>homouwu' (STEAM_0:0:41908082).

**Comment by ghost** [comment]
How is this being achieved? Starfall or e2 I'm assuming

**Comment by Cynosphere** [comment]
model manipulator tool

**Comment by ghost** [comment]
Epic

**Comment by TW1STaL1CKY** [comment]
Invalid models can't be used by the model manipulator tool anymore
