### ISSUE TITLE
web bowser

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#44]
i hate when im trying to play a video and when i close it the console says this "[HTML] event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future."

and i can't stop the video... FIX IT!

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by LUModder** [comment]
Hey look, something we can't fix because of how outdated Awesomium is...

**Comment by PotcFdk** [comment]
I don't think this is entirely unfixable. What kind of videos is this even about? PlayX? YouTube?
Obligatory @ArcticFqx ping.

**Comment by Cynosphere** [comment]
Dunno if it's happened again, reopen if it has
