### ISSUE TITLE
Selling items to NPCs that dont have the item makes the sold item go poof

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#440]
Example: cursed bullets at the tavern npc

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by ghost** [comment]
Don't know if someone fixed this: https://i.imgur.com/V1kBWZb.png
Just tried and got this message. Confirm if still valid?

**Comment by cdr1996** [comment]
Since I can't reproduce this and no one has commented since I'm going to close this issue.
