### ISSUE TITLE
Update TylerB's moneyRequest E2 Functions

### ISSUE THREAD

**Issue by djsime1** [Metastruct/issues#442]
https://steamcommunity.com/sharedfiles/filedetails/?id=259174593  
Newer version has heckton more useful functions

**Comment by ghost** [comment]
I don't know who's responsible for updating non meta content so you're probably gonna need to ask around about this

**Comment by Python1320** [comment]
updated 
ref: https://gitlab.com/metastruct/internal/srvaddons/-/commit/9647964e4b30b7934b2cfe836efbed3823f839aa
