### ISSUE TITLE
Chatsounds Taken A Shit

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#443]
Everytime I try to enable or use chatsounds, it breaks with this error.
![screenshot](https://i.imgur.com/Ye6ZPZu.png)

Bug reported by 'Jarvis787' (STEAM_0:1:549837880).

**Comment by cdr1996** [comment]
Can confirm that errors like these do happen still and will break chatsounds entirely unless someone reloads them via .newchatsounds command.

**Comment by cdr1996** [comment]
Added medium priority label here since chatsounds breaking still seems to happen fairly frequently and stack traces like this are common.

**Comment by cdr1996** [comment]
This seems to be an old issue and to the best of my knowledge chatsounds were recently updated to be more stable. If any more issues arise with chatsounds please reopen this/create a new issue.
