### ISSUE TITLE
:you: should not count as a mention

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#448]
Especially it should not trigger the afk mention popup thing.

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by ghost** [comment]
Hoping earu will get on this

**Comment by cdr1996** [comment]
Still relevant as of today from what I've seen. @Earu ?

**Comment by Earu** [comment]
working as intended

**Comment by cdr1996** [comment]
💀

**Comment by cdr1996** [comment]
Closing for now, I personally don't like the :you: thing causing a mention, but Earu doesn't seem intent on changing this. Reopen if needed.
