### ISSUE TITLE
Luadev error that occasionally happens when executing

### ISSUE THREAD

**Issue by djsime1** [Metastruct/issues#449]
(LuaDev repo doesn't have issues enabled)

```
[luadev-master] addons/luadev-master/lua/luadev/luadev.lua:395: bad argument #1 to 'CRC' (string expected, got nil)
  1. CRC - [C]:-1
   2. CheckStore - addons/luadev-master/lua/luadev/luadev.lua:395
    3. RunOnSelf - addons/luadev-master/lua/luadev/luadev.lua:407
     4. unknown - addons/luadev-master/lua/luadev/socketdev.lua:49
      5. v - addons/luadev-master/lua/luadev/socketdev.lua:142
       6. unknown - lua/includes/modules/hook.lua:84
```

Using the latest LuaDev files with VSCode extension on Windows 10 / GMod 64-bit. On one occasion I couldn't execute any more scripts from VSCode until I restarted the game.

**Comment by Cynosphere** [comment]
There's not really any good way to fix this considering its just socket reading that breaks occasionally.

You don't need to restart everytime it breaks, just include `luadev/socketdev.lua`

And to mitigate, `luadev_store 0`, saves you some hard drive space too

**Comment by Earu** [comment]
There are proper ways to handle a socket pipe only closed on one side, heartbeat etc. .. To add to this you can have exponential reconnect attempts and then if it fails more than lets say 3 - 5 times you can prompt the user to restart the process
