### ISSUE TITLE
hal1320: slap command is broken

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#45]
beh the slap is ded AttributeError: 'Config' object has no attribute 'admins' (file "/home/hal1320/sopel/sopel/config/__init__.py", line 166, in __getattr__)

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by PotcFdk** [comment]
Fixed by merging https://github.com/sopel-irc/sopel-extras/pull/75
