### ISSUE TITLE
listening spam

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#451]
those listening keeps on spamming in chat https://i.imgur.com/V7EcBfp.png no one has fixed the delay or remove it yet... it's useless to know who's watching when it keeps on spamming on chats (i know it's on epoe but i overrided it to epoe instand of chat.)

Bug reported by '^7Bjoern90 At Work' (STEAM_0:1:42844056).

**Comment by TW1STaL1CKY** [comment]
Removed the automatic chat print whenever someone subscribes to the mediaplayer you're subscribed to.
Now when you subscribe to a mediaplayer, it will remind you of the "!listeners" command if you do want to see who else is subscribed.
