### ISSUE TITLE
advert

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#452]
ppl shouldnt be able to spam that command.. https://i.imgur.com/bpAvMtE.png  if so i would love to get delay back OR make a convar to prevent ALL rp commands...

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by bjoern90** [comment]
forgot to add that it bypasses gag too

**Comment by TW1STaL1CKY** [comment]
I can't fix the gag bypassing since gag is a clientside thing, but I've made the cooldown for /advert and /ooc longer. I've added a character limit for both commands as well.
