### ISSUE TITLE
Fishing Rod

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#454]
it seems using b button wont open the fishing rod shop anymore for some reason... so we have to use fishing_mod_menu for now or??

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by 0x098** [comment]
Currently it checks if there is anything bound to it. Opens if no binds exist on b key.
"unbind b" and it should work.

https://github.com/Metastruct/fishingmod/blob/master/lua/fishing_mod/cl_init.lua#L121

**Comment by ghost** [comment]
**You** can always bind it via console
Like this: **bind key_choice "fishing_mod_menu"**
best regards.
