### ISSUE TITLE
easychat bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#455]
blocked players chat can still be shown when doing:

15:57 - fag WR1 PUPPY@server: loki:GetActiveWeapon().Secondary.Force = 131071

or

doing the "!goto" stuffs

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by Earu** [comment]
It's actually related to the metastruct networking of chat messages, but fixed nonetheless.
