### ISSUE TITLE
blocked chat

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#456]
even when players chat is blocked i still see the s/// thingy "Деку thinks yes meant: my dick is spinning"

Bug reported by '^7Bjoern90<stop>' (STEAM_0:1:42844056).

**Comment by cdr1996** [comment]
This would require EasyChat to work with sed4chat, something I don't think anyone could be bothered doing since its a really minor thing and only likely to cause frustration to you and you alone. If anyone wants to go ahead and implement this be my guest but otherwise this issue could be closed.
