### ISSUE TITLE
a weird infinite seagull glitch i found..

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#457]
so if you catch any melon pet catch, (for example, an angry baby), freeze it and then catch it again with hook but not in water, it makes another seagull? please patch this, as i dont want this to effect other people's fishing peacefully sessions.

Bug reported by '&4yes' (STEAM_0:0:206795819).

**Comment by 0x098** [comment]
They dont merge or barely fix fishingmod. Just kill the seagulls and farm the moneys :)

**Comment by cdr1996** [comment]
Still relevant or fixed by someone?

**Comment by cdr1996** [comment]
I'm told by @0x098 that this was fixed and he has made pull requests to fishing mod in the past. Closed and assumed fixed unless anyone finds otherwise.
