### ISSUE TITLE
MTA bounty

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#458]
when a bounty is issued on yourself you get a spam of these https://i.imgur.com/W7o9TMt.png when you jump that happens  when you accept somebody elses bounty too...

Bug reported by '^7Bjoern90 At Work' (STEAM_0:1:42844056).

**Comment by cdr1996** [comment]
Not sure if still relevant, but I think MTA issues are now separate from Meta Construct issues as MTA is on server #3. Ask Earu for clarification perhaps or report it here: https://steamcommunity.com/groups/metastruct/discussions/2/2992044576642354304/

I should also imagine Earu has fixed this already.
