### ISSUE TITLE
keep talking and nobody expoldes

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#46]
beh when is mitterdoo fixed the bomb error? bec snip and mike is playing it.. plus the console is spamming like shit.. like sound is missing and this http://i.imgur.com/Shnkuzj.jpg

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by PotcFdk** [comment]
I have no idea what this is about. @mitterdoo? Can you fix whatever he needs to have fixed?

**Comment by LUModder** [comment]
I knew I shouldn't of told Bjoern of !bug

**Comment by mitterdoo** [comment]
should no longer be spamming the console anymore. i'm not sure what could be causing it to be spammed in the first place because the line that prints to console should only be called once.

**Comment by Cynosphere** [comment]
I'm assuming this is fixed
