### ISSUE TITLE
the party mode command is broken

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#47]
it is your fault, flex

Bug reported by '<color=255,0,0>Knotcake' (STEAM_0:1:19269760).

**Comment by PotcFdk** [comment]
>@LUModder's fault
-- cake

**Comment by LUModder** [comment]
I'll fix it when I get home

**Comment by notcake** [comment]
thank you based flexen

**Comment by LUModder** [comment]
Fixed
