### ISSUE TITLE
nil function being called in ply:IsAdmin()

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#48]
[Hook] HUDPaint -> "FlexHUD" failed: lua/aowl/aowl.lua:2000: attempt to call method 'IsFullyAuthenticated' (a nil value)
stack traceback:
	lua/aowl/aowl.lua:2000: in function 'IsAdmin'

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by PotcFdk** [comment]
@notcake!
