### ISSUE TITLE
scoreboard error...

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#49]
this what happed if i open the scoreboard.. 
[ERROR] lua/aowl/aowl.lua:2000: attempt to call method 'IsFullyAuthenticated' (a nil value)
  1. IsAdmin - lua/aowl/aowl.lua:2000
   2. f - lua/fast_addons/client/scoreboard.lua:2046
    3. RefreshTags - lua/fast_addons/client/scoreboard.lua:2123
     4. RefreshTags - lua/fast_addons/client/scoreboard.lua:2880
      5. unknown - lua/fast_addons/client/scoreboard.lua:3145

FIX IT!

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by LUModder** [comment]
Reported in #48
