### ISSUE TITLE
World deletion bug with tesla guns and core

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#5]
World disappears when you take two tesla guns by the core and set self destruct on both of them at the same time.

Bug reported by '<color=33,91,51>Flex' (STEAM_0:0:58178275).

**Comment by PotcFdk** [comment]
![screenshot by Flex](http://i.imgur.com/U43qjLa.png)

**Comment by Cynosphere** [comment]
Fixed via mapdata commit 2743
