### ISSUE TITLE
Add "load from url" to lua editor

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#50]
* Add "From URL" to open or load button
* Praise pastebin and hastebin links as raw data (maybe other paste sites too)

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by LUModder** [comment]
Might as well assign myself to it since I'm working on it.

**Comment by LUModder** [comment]
Added via srvaddons commit 11504, please close.
