### ISSUE TITLE
Redeem - Code parsing

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#53]
This affects the !redeem menu.
This isn't a huge problem, but I'm reporting it anyway.

When you enter a code including a '/' or a '\' and pressing 'redeem', the menu is still waiting for a callback.
This code is never called in this case : 

net.Receive (Tag, function ()
	local type = net.ReadString ()
	if type == GIFTCODE_OPENMENU then
		return OpenDialog ()
	elseif type == GIFTCODE_RD_SUCCS then
		if IsValid (Frame) then
			Frame.Info:SetTextColor (Color (0,195,15))
			Frame.Info:SetText ("Success!")
		end
	elseif type == GIFTCODE_RD_ERROR then
		if IsValid (Frame) then
			Frame.sendbutton:SetDisabled (false)
			local err = net.ReadString ()
			Frame.Info:SetTextColor (Color (195,15,0))
			Frame.Info:SetText ("There was an error: " .. tostring (err))
		end
	end
end)

Bug reported by '<color=0,144,255>Myrage2000' (STEAM_0:1:45897995).

**Comment by PotcFdk** [comment]
Should be fixed now, thanks.
