### ISSUE TITLE
MSA computer - KeyCode

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#55]
Players can't use the msa computer when it's locked.
This is currently done by checking if the computer is locked before calling StartKeyCodeI()

If the computer is locked, players can still 'lua_run_cl StartKeyCodeI()' to use it.
The net.Receive("KeyCodeSvR",function(len,ply) end) doesn't check again if the computer is locked.

Bug reported by 'Myrage2000' (STEAM_0:1:45897995).

**Comment by Cynosphere** [comment]
The var for lockthis needs to be networked.

**Comment by Tenrys** [comment]
uh what? never knew it could be locked?

**Comment by Cynosphere** [comment]
Well of course, it's only locked for players

**Comment by ghost** [comment]
Fixed.
