### ISSUE TITLE
Network easylua values for crosslua

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#56]
As title says

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by Python1320** [comment]
this, here, these, we, me? ????

**Comment by LUModder** [comment]
And names, entity ids (ex _1) and probably some others, this, here and there don't really need to be networked because it's not gonna give out good results.

**Comment by SpiralP** [comment]
fixed in https://github.com/Metastruct/luadev/commit/3331317f7e87867d21752e77964abc8314987f0b and r12401
now it should complete entity names and returns more than one value :8ball:
