### ISSUE TITLE
World entities can be manipulated from the context menu

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#63]
Using the context menu and right clicking on world entities, non-admins can manipulate them. Such abilities include driving (and possibly more, like removing them).

Bug reported by 'Knotty' (STEAM_0:0:19576364).

**Comment by ghost** [comment]
The dreaded elevator is the only one I found.

**Comment by Cynosphere** [comment]
Need a list of more that can do this

**Comment by danielga** [comment]
The wall chargers in RP also are affected.

**Comment by Python1320** [comment]
elevator was supposed to be such a thing. Wall chargers not so much, but they're Lua-generated so they don't enjoy world protection.

**Comment by Tenrys** [comment]
I don't recall this being an issue anymore.

**Comment by Tenrys** [comment]
Also nice, assigning ME in particular even though there were other developers capable of fixing it.
