### ISSUE TITLE
Metastruct Fireworks discriminate against UTC+0830

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#65]
The people in North Korea won't get fireworks at the right time because of you.

https://www.timeanddate.com/time/time-zones-interesting.html

Bug reported by '<color=255,0,0>Knotcake' (STEAM_0:1:19269760).

**Comment by danielga** [comment]
[How about... NO!](https://www.youtube.com/watch?v=lITBGjNEp08)

**Comment by Python1320** [comment]
Don't forget chinese new year

**Comment by Cynosphere** [comment]
I don't think Meta is whitelisted in the NK intranet.

**Comment by PotcFdk** [comment]
What @LUModder said.
