### ISSUE TITLE
Hide blocked markup in names

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#66]
It's annoying to see hsv tags in names.

**Comment by Tenrys** [comment]
If you want them to show up in chat, enable some cvar I added a while ago.
But yes, I should make it hide if it's disabled.

**Comment by PotcFdk** [comment]
What's the point in having hsv tags in your name when they don't work? Why not simply remove them from your nick?

**Comment by Tenrys** [comment]
The thing is some people put them in their names to have them show up in nametags, regardless of whether you can see them in chathud or not.

**Comment by Tenrys** [comment]
I'm working on making nametags work with the convar I made a while ago for name decorations in ChatHUD.

**Comment by Tenrys** [comment]
done
