### ISSUE TITLE
shadowban feature pls

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#67]
for trolls
coh and chatsystem need modification
shadowbanned users should see their own messages in chat

Bug reported by '<color=255,0,0>Knotcake' (STEAM_0:1:19269760).

**Comment by notcake** [comment]
also can we somehow shadow their prop physics so it only happens on their client? :v

**Comment by PotcFdk** [comment]
Will this turn into an alternate reality for banned people where they think everything's alright, but to other players, they simply stop existing?

**Comment by edunad** [comment]
@PotcFdk if that is the case, i demand a blackhole sucking the player in when you ban him

**Comment by bmwalters** [comment]
![:thumb:](http://i.imgur.com/Ljy1vG2.png)

**Comment by danielga** [comment]
Pure Lua vphysics simulation, lvphysics.
The shitty port of the shitty physics engine!

**Comment by Techbot121** [comment]
watch it become more stable than vphysics.

**Comment by bmwalters** [comment]
:+1:

```
3:44 PM - !𝖼𝖺𝗄𝖾: when you shadowban someone
3:44 PM - !𝖼𝖺𝗄𝖾: can we fork srcds
3:44 PM - !𝖼𝖺𝗄𝖾: and drop them off one of the srcds instances
3:45 PM - ＭｅｔａＭａｎ: this meme is going too far
3:45 PM - !𝖼𝖺𝗄𝖾: the packets of other players will have to be duplicated
3:45 PM - !𝖼𝖺𝗄𝖾: will copying packets to the shadowbanned instance even work
3:45 PM - PotcFdk: http://cs.3kv.in/?s=privilege%20check%232*1
3:46 PM - PotcFdk: probably
3:46 PM - PotcFdk: we have binary modules
3:46 PM - PotcFdk: can't we IPC?
3:46 PM - PotcFdk: or something
```

**Comment by zxz41** [comment]
Is this actualy being worked on, or is it a joke? And if so can we close it.

**Comment by PotcFdk** [comment]
It will be closed when internal discussions end.

**Comment by Tenrys** [comment]
Did they end yet?

**Comment by bmwalters** [comment]
Nope.

**Comment by PotcFdk** [comment]
They did.
