### ISSUE TITLE
tod renders everything black on non gm_construct_m maps

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#69]
Dunno why it does this. I know that's a main reason why we removed tod on server 2 cause it wasn't playing nice with m3ta maps but it'd be nice to have it back.

**Comment by edunad** [comment]
One of the big ussues why we disabled tod on m3ta, was that, it messed up shadows on textures  and the only way to fix that (if i recall) was to run reloadmaterials on clients, or spawn a light and removing it

**Comment by Cynosphere** [comment]
I'm singleplayer testing this on a different map and I don't have the black bug but this happens and it wont fix itself

![](https://my.mixtape.moe/pqttso.png)

**Comment by Cynosphere** [comment]
So no one's gonna fix it, huh?

**Comment by edunad** [comment]
Already said you get textures issues. Just look at PACS in meta build zone, messed up

**Comment by Cynosphere** [comment]
I never see any PAC issues in build area

**Comment by edunad** [comment]
Ligthing issues in general

**Comment by zxz41** [comment]
What map

> I'm singleplayer testing this on a different map and I don't have the black bug but this happens and it wont fix itself

**Comment by Cynosphere** [comment]
Map I was using was Genesis but it does it with most maps

**Comment by Cynosphere** [comment]
Seriously, no one CBA to fix this still? I'd love to use this on FlexBox instaed of laggy, pirated Simple Weather :v

**Comment by PotcFdk** [comment]
> I'd love to use this on FlexBox instaed of laggy, pirated Simple Weather :v

Stop stealing stuff and making people feel like they should be helping you with that, even.
Jesus. Even marking this as "priority". Can it get any more selfish?

**Comment by Cynosphere** [comment]
Don't fix a bug that's existed for 2+ years then... I don't really care if you're gonna act like that about it :v

**Comment by Tenrys** [comment]
aren't you a developer? fix it yourself if it bothers you that much.

**Comment by Cynosphere** [comment]
> aren't you a developer? fix it yourself if it bothers you that much.

I'd fix it if I knew what was wrong

**Comment by CassiaPurple** [comment]
Could it possibly be something in the code that controls the lighting based on the position of the sun? That's just based off initial observation also idk why I even give advice I don't lua.

_edit_
Also could the normal meta maps have special light maps that is only there and the other maps don't have them and the code uses them

If I knew how to lua I would attempt to figure it out myself

**Comment by Tenrys** [comment]
I think that's fixed, I saw a commit made not too long ago to make it work with maps that don't have an env_sun entity. You could try it it out and give us results?

**Comment by ajloveslily14** [comment]
Seems pretty fixed to me
