### ISSUE TITLE
GAuth bugs on join

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#70]
[13:09] Player [19][Flex] ERR:  
    gauth/gauth.lua:301: Tried to use a NULL entity!
         1: GetFriendStatus (NULL, "Tried to use a NULL entity!") [[C]: -1]
         2: (_ = { table: 0x6968e198 }, ply = NULL, userId = "STEAM_0:1:86968752", isLocalPlayer = false) [gauth/gauth.lua: 301]
         3: xpcall (function (message)) [[C]: -1]
         4: DispatchEvent (self = { table: 0x680f3ee0 }, eventName = "PlayerConnected", { table: 0x6968e198 }, NULL, "STEAM_0:1:86968752", false) [glib/events/eventprovider.lua: 86]
         5: () [glib/servers/playermonitorproxy.lua:
[13:09] Player [19][Flex] ERR: Error in hook PlayerConnected: Func:(gauth.lua: 251-308)!

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by ghost** [comment]
Check if the player is valid before using it in that function ?

**Comment by PotcFdk** [comment]
Still relevant?
@notcake have you taken a look at this?

**Comment by notcake** [comment]
Fix ETA: heat death of universe.
