### ISSUE TITLE
Adv Teleporter Errors

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#71]
[15:56] lua/entities/gmod_advteleporter.lua:221: attempt to index a nil value
1. GetOwnerPlayer - lua/entities/gmod_advteleporter.lua:221
   1. CheckFriendship - lua/entities/gmod_advteleporter.lua:232
   2. Teleport - lua/entities/gmod_advteleporter.lua:261
      1. unknown - lua/entities/gmod_advteleporter.lua:332

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by SpiralP** [comment]
probably fixed in r12348 and a few other revisions
