### ISSUE TITLE
!goto doesn't work for certain nicks

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#72]
Apparently it happens when there are markup tags in the nick.

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by notcake** [comment]
Here be dragons :dragon_face:

**Comment by Cynosphere** [comment]
I already reported this forever ago but no one fixed it

**Comment by Cynosphere** [comment]
Yeah, #18 was when I reported it
