### ISSUE TITLE
Cinema lights are broken on gm_construct_m_128

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#73]
They won't turn dark when a video starts.

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by zxz41** [comment]
@PotcFdk Running `ent_fire light TurnOff` seemed to work. Likely lua side. Can't do much about it myself.
http://i.imgur.com/wlpbsam.jpg
(Ignore the colored stuff)

**Comment by PotcFdk** [comment]
@Python1320 the entity classes seem to be off. Have they changed in the vmf?

**Comment by ghost** [comment]
I remember the keycode 'lightsout' in the MSA computer did something on the theater lights, no ?

**Comment by PotcFdk** [comment]
That's unrelated to this issue. I know what's causing it, but I don't know why things were changed the way they were changed.

**Comment by zxz41** [comment]
> myrage2000 commented 4 hours ago
> I remember the keycode 'lightsout' in the MSA computer did something on the theater lights, no ?
> 
> Owner
> PotcFdk commented 3 hours ago
> That's unrelated to this issue. I know what's causing it, but I don't know why things were changed the way they were changed.

I don't see how it is completely unrelated to this issue. It could have been messing up the lights. Did you find out why they were changed?

**Comment by PotcFdk** [comment]
@zxz41 As I already pointed out [here](https://github.com/Metastruct/issues/issues/73#issuecomment-169802950), the entity classes seem to have changed. This is a recent observation that I made when I last played a video in the cinema and looked up the function source ingame. The MSA computer has nothing to do with this.
I am not actively working on this bug.

**Comment by zxz41** [comment]
@PotcFdk oh right. My fault

**Comment by ghost** [comment]
Does this still matter since we are on a new version now?

**Comment by PotcFdk** [comment]
I don't think so. If there's any current issue with cinema lights, please re-open.
