### ISSUE TITLE
SCAP blocker?

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#74]
Dunno if anyone wants to do this, but like a block on all or based on like friends broadcast of SCAPs you can receive. Would be useful if someone just decided to spam you with useless SCAPs and they won't stop.

EDIT: I mainly posted this as if people see this as needed/wanted or not

**Comment by Zeni44** [comment]
It would be good to have something like that.

http://pastebin.com/uQKW8S7R
I got this to hide the scap popup. It doesnt block it but atleast it keeps that text off your screen ( except the chat message one )

EDIT: I made a new scap block version.
http://pastebin.com/xdTfVw0t 
It completely blocks scap now, no more messages.

**Comment by Cynosphere** [comment]
Yeah but I was thinking disabling even sending to that person and when you hover over the disabled button it says "%s has disabled receiving scaps (from you)"

**Comment by PotcFdk** [comment]
Why do we have to make every single feature toggleable? It seems a bit annoying to me.

**Comment by Cynosphere** [comment]
Because people decide to abuse it and it can get really annoying to just have random SCAPs sent to you that aren't related to anything. togglegoto was invented to not be annoyed by other players so yeah. It's something we can't fully stop but at least temporarily stop.

**Comment by PotcFdk** [comment]
Why is it something that "we can't fully stop"? Shouldn't SCAP spam be handled just the same way chat spam is?

**Comment by zxz41** [comment]
Because it's what the community wants.
EDIT: And Metastruct already (still) lack a lot of fine tuned blacklisting and blocking (from personal experience)

**Comment by edunad** [comment]
We could just implement a cooldown on scap sending. Perhaps 2 mins cooldown after sending a scap?

**Comment by PotcFdk** [comment]
Nah, that could be quite annoying. A cooldown for scaps with multiple recipients, perhaps?

**Comment by edunad** [comment]
You could apply the cooldown to that user you just sent instead of a global one

**Comment by notcake** [comment]
"Block future SCAPs from this user this session" button on the SCAP image window?

**Comment by Zeni44** [comment]
Couldnt they just rejoin to avoid it ?
Would be pretty annoying though to block that person every session.
Make it forever instead of current session.

**Comment by notcake** [comment]
No it'd be a Steam ID block for the duration of the blocking user's session.

**Comment by edunad** [comment]
@notcake i like your solution (hes not threating to eat me, totally) , my only concern would be if you missclicked, how could you unblock?

**Comment by notcake** [comment]
rip

**Comment by zxz41** [comment]
Couldn't you/we just make a blacklist in the data folder that contains the player ID followed by what to block? For now it could just be blocked with `!block failcake,scap` and `!unblock failcake,all` and later on get it's own tab in the chat window? (or whatever that goes)

The blacklist txt file could look something like this

```
STEAM_0:1:1234567=scap,chat
STEAM_0:1:7654321=chat
STEAM_0:1:9876543=all
```

A few other functions like `GROUP:banned=all` and `TAG:pirate=voicechat` could be really nice too (Finally a way to automatic mute Russian kid pirates)

**Comment by Cynosphere** [comment]
@zxz41 So pretty much extend out friends broadcast to be more than just allow and block but for everything else in between too

**Comment by notcake** [comment]
Flex call it safe_space.lua

**Comment by Zeni44** [comment]
Wouldnt it be better though to block over the scap menu with a button ( like @notcake said ) and not chat since players are going to be like
"Y U BLOCK ME" 
Except if you add <code>return ""</code> at the end of the code

**Comment by notcake** [comment]
BUT TOASTY THAT SAFE SPACE ISN'T SAFE AND PADDED ENOUGH. REALITY CAN STILL SHINE THROUGH.

**Comment by Tenrys** [comment]
@LUModder added this a while ago I think?
