### ISSUE TITLE
m3ta mapdata misaligned

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#75]
Apperently FailCake moved the whole lobby upwards so all the gotos, the core and all that is broke.

**Comment by PotcFdk** [comment]
Every dev can fix this, not just @edunad.

**Comment by edunad** [comment]
Don't fix it yet, python or who ever did it, when adding the flatgrass moved the map even more, breaking all the m3ta screens, ill keep working on the map soon, and try to add the build zone

**Comment by Python1320** [comment]
mapdata offsets should be relative to a landmark, but a system for this is still pending :(
