### ISSUE TITLE
Meta Construct is cancerous...

### ISSUE THREAD

**Issue by danielga** [Metastruct/issues#76]
...and nothing good or productive has ever come out of it.

We're also the gayest server in all of Garry's Mod.

We need solutions to fix this deeply rooted problem in our community.
Maybe a code of conduct.

[Source](https://facepunch.com/showthread.php?t=1500597&p=49483625&viewfull=1#post49483625)

**Comment by SwadicalRag** [comment]
:+1:

**Comment by kalis0x** [comment]
You should unban hvhgod :8ball:

**Comment by SpencerSharkey** [comment]
:100:

**Comment by kalis0x** [comment]
:1234:

**Comment by edunad** [comment]
You should update the post with the reason of hes ban (if he was, in fact, banned)

**Comment by marcogravbrot** [comment]
We should put him in an alternate universe!

**Comment by zxz41** [comment]
> Nothing ever good or productive has ever come from the people who go on that server.

Except all the security patches and chatsounds and whatnot

**Comment by zxz41** [comment]
^

**Comment by Cynosphere** [comment]
-snip being serious on a joking matter based issue-

**Comment by danielga** [comment]
This is not proper behavior @LUModder. I'll have you removed at once if you keep it up.

**Comment by ghost** [comment]
:hankey:

**Comment by SwadicalRag** [comment]
#SkidLivesMatter

**Comment by kalis0x** [comment]
#TylerWearingMemesMatter

**Comment by brandsjek** [comment]
just got my mail server back up, i just see my inbox spammed with this... what is this about? looks like the OP is butthurt because he was banni'd?

**Comment by danielga** [comment]
The joke is dead. Everybody go home.

**Comment by SwadicalRag** [comment]
you're ded
