### ISSUE TITLE
two methods of having an invisible name

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#79]
These won't allow you to have no name at all but they still look invisible in chat.

1st Method (probably the most known):
- have a single color tag in your name

2nd Method (only displays invisible in chat)
- start by adding a ^color code (^1-9) in your name
- add an invisible character
- add an invalid ^ code (^ followed by a letter, e.g. ^G)

100% unplayable devs pls fix

Bug reported by 'Ghosty' (STEAM_0:0:62588856).

**Comment by ghost** [comment]
*reported by me
also what the fuck the 2nd method got butchered, can someone edit that please

**Comment by Tenrys** [comment]
this doesn't really matter though does it?

**Comment by Cynosphere** [comment]
Does and it doesn't, its a hassle to get someone's ent ID for a ban if
they're using a blank name, even more if two people are.

**Comment by Lixquid** [comment]
However, people using names that contain no Latin script, like Russian
players, also have "untargetable" names, completely by accident. It's
pretty much an impossible problem to force someone to have a targetable
name at all times without some serious code.

A better alternative for devs is to turn on Dev mode for the scoreboard,
and use the EntID syntax (`_123`).

**Comment by PotcFdk** [comment]
I personally have an issue with those people because you can't talk to them. Even Player[number] would be better than an invisible name. It just feels so annoying to see chat messages without any name.

**Comment by Lixquid** [comment]
I have no opinion about community guidelines regarding blank names; I can
see why they'd be annoying. My stance is only that a programmatic solution
would be difficult.

**Comment by ajloveslily14** [comment]
Seems fixed
