### ISSUE TITLE
Hooks worth looking into according to profiler.

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#8]
autorun/tod.lua:814           				sampled      2 times. Took 0.30s
glib/garrysmod/servers/playermonitor.lua:35 sampled      3 times. Took 0.15s
autorun/spellsys.lua:136      				sampled      4 times. Took 0.19s
fast_addons/player_grab.lua:123 			sampled      4 times. Took 0.19s
autorun/csweapons.lua:333     				sampled      3 times. Took 0.15s
weapons/tf_weapon_skullcutter.lua:389 		sampled      2 times. Took 0.14s
weapons/tf_weapon_skullcutter.lua:449		sampled      2 times. Took 

Bug reported by 'Python1320' (STEAM_0:0:13073749).

**Comment by danielga** [comment]
`weapons/tf_weapon_skullcutter.lua:449 sampled 2 times. Took `

@PotcFdk, do we have a report length limit?

**Comment by PotcFdk** [comment]
The only things that limit the report length are:
* the GitHub API
* the maximum size of a net message

**Comment by Python1320** [comment]
Stared at the hooks, not much I can do without major rewrites. Some could maybe just be removed or recoded to not use think hooks over all players, etc
