### ISSUE TITLE
Pointless drama needs to stop

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#80]
I know this isn't a technical issue and all, but it needs to be addressed because I know I and other devs are tired of seeing/hearing it. The pointless arguments need to stop. Yes, I am the cause of it mostly, but I will stop if people stop bringing it up.

Key people: Lixquid, Henke, Toasty

**Comment by notcake** [comment]
tl;dr of drama please

**Comment by Cynosphere** [comment]
Henke thinks I'm spreading lies. Lixquid annoying other players with certain scripts he works on or tests and people call him out on it and he just argues about it. Toasty just makes stupid pointless comments on the drama

**Comment by danielga** [comment]
This should have been posted on the Metastruct Steam forums. They're kinda shit but everybody on Metastruct is on Steam so there's nobody that can say "I couldn't post anything because I don't have an account!!! And I'm not going to make one just to _insert expletive here_!!!". But ok, we'll see.

**Comment by Cynosphere** [comment]
I put it on here because I more wanted devs to comment on it and the people I mentioned I know have a github account.

**Comment by Lixquid** [comment]
Useless Issue, keep your personal issues out of the technical issues repository.

**Comment by Cynosphere** [comment]
It's not really personal issues when the whole server knows about it :v

**Comment by Zeni44** [comment]
Excuse me? I see you and Lix arguing again and you are blaming me for apparently telling something and also respond with "Fuck you Toasty" so I responded back with fu.
That was literally the only "stupid pointless comment" I can remember.
But well this is closed now.

**Comment by zxz41** [comment]
@LUModder @ToastyEngineer 
**Stop complaining here.** This is meant for technical issues. As @Lixquid said

For any other issues related to drama etc. Contact a high tier dev on Metastruct, @PotcFdk on IRC **OR** post it on http://steamcommunity.com/groups/metastruct/discussions/1/

Just make sure to do it in the next ~48 hours (or else they'll concider it "not related" (based on own experiences) even tho they don't have a clear guideline for reports, which is ridiculous if you ask me.)

**Comment by Cynosphere** [comment]
@zxz41 Stop back seat moderating.

**Comment by Zeni44** [comment]
^

**Comment by Lixquid** [comment]
The issue is closed. All parties should take this discussion elsewhere.
