### ISSUE TITLE
Adv. Duplicator Area Copy is broken

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#83]
y advdupe2 no work

Bug reported by '<color=119,146,0>UnKnao' (STEAM_0:1:33890317).

**Comment by Lixquid** [comment]
> 15:43 - [IRC ✓] PotcFdk: I'm going to close that bug because it's shit
> 15:43 - [IRC ✓] PotcFdk: re-report with details, if you're taking this seriously

**Comment by Cynosphere** [comment]
AFAIK, Area Copy has been buggy saying "invalid head entity for ghosts". I suspect it's the area_dupe file in fast_addons maybe but I haven't tried to use Adv Dupe 2 on other servers than Meta and mine.

**Comment by Cynosphere** [comment]
[This might of fixed area copy, untested though](https://github.com/garrynewman/garrysmod/commit/277f36ca2698debd013c5526bb6ebeaf43d293fa)

**Comment by Tenrys** [comment]
How could a removed unneeded local variable fix anything?

**Comment by PotcFdk** [comment]
I'd say you better report this [here](https://github.com/wiremod/advdupe2).
