### ISSUE TITLE
Advdupe 2 doesnt work after a lag out

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#86]
advanded duplicator 2 always says duplicator is busy after a big lag out ( prevents me from chatting too), the only way it resets is if the server crashes or restarts

Bug reported by '<color=119,146,0>UnKnao' (STEAM_0:1:33890317).

**Comment by PotcFdk** [comment]
Is #83 related?

**Comment by Cynosphere** [comment]
Shouldn't a retry fix this?

**Comment by PotcFdk** [comment]
That's not a fix, that's a workaround.

**Comment by Python1320** [comment]
Make a new bugreport if not fixed. Advdupe2 bugs should be filed here: https://github.com/wiremod/advdupe2
