### ISSUE TITLE
uuh plate bug?

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#87]
when i spawn a 32x32 plate this happes http://i.imgur.com/smu9Sjv.jpg is this a bug or woot? or it's just to prevent players to spam them? how can i spawn my private box .-.

FIX IT FILEX!

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Cynosphere** [comment]
It was probably spam restricted for a reason
