### ISSUE TITLE
Precache limit in SrvInfo needs updating

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#88]
nvm it's fixed after server restarted... maybe just check if there's any bug that triggered it? btw i never seen the model could reach to 102% O.o http://i.imgur.com/ZY0Rb2B.jpg

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Cynosphere** [comment]
Precache got upped to 4096 in latest update but SrvInfo hasn't been updated

**Comment by ghost** [comment]
Looks like it has been fixed.
![alt text](http://puu.sh/mZEAR/1b852802a5.jpg)

**Comment by SpiralP** [comment]
we still restart after 2048 though because after, models start to appear differently on client than what they are on server
not sure if this has been fixed yet though, nothing about it has been in the update logs

**Comment by ghost** [comment]
Already fixed.
