### ISSUE TITLE
Mapdata needs more sit nodes and some need to be fixed

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#90]
One's to fix:
![](http://i.imgur.com/IeTTRug.jpg)
One's to add:
- Corner benches
- Bench next to bathroom/suana enterence
- Spawn benches
- Demoscreen benches

**Comment by PotcFdk** [comment]
@Python1320 / @Metastruct/mappers 
What's the status on this?

**Comment by KabusDev** [comment]
No info hit nodes are present on the lobby map, it's beyond me how these work

**Comment by Myaats** [comment]
These are all in mapdata and need to be done manually, I can probably help Kabus find the right offset so we can make this map based @KabusIblis ?

**Comment by KabusDev** [comment]
likely offsetting existing nodes would be easier than me placing nodes in hammer and praying they work

**Comment by Cynosphere** [comment]
Closing since old and was m2 map issue.
