### ISSUE TITLE
the togglegoto... and banni bug?

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#93]
ok sorry if i suck at the bug reporter... all i ment players can goto to players even they toogled it.. fix it tho..

plus is banned players allowed to use the inventory? bec the french minebag keep using poison while im dragged him to the rp to steal all coins from him .-. (i know the fucking coins are still useless! FFS)

suck that toasty! happy now?!?

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Cynosphere** [comment]
You didn't have to make a new issue for it, you could of reopened the other one...

**Comment by PotcFdk** [comment]
See #92
