### ISSUE TITLE
Scoreboard - Time Column Icon Bug

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#94]
Scoreboard adds the vcard icon (time column) to IRC, Other Servers, etc. even though they don't have a value.

Screenshot: 
![](http://puu.sh/mOi4W/73b1e4834d.jpg)

Bug reported by '<color=255,120,0>Google' (STEAM_0:1:66459838).

**Comment by PotcFdk** [comment]
Reopen if this is still a thing. I've never seen this.

**Comment by Cynosphere** [comment]
Feature not a bug, if you click on the time icon it switches to account age

**Comment by PotcFdk** [comment]
@LUModder The bug is that the icon shows even though the player has no value.

**Comment by Lixquid** [comment]
Confirmed still exists.

![](http://i.imgur.com/UyZQC9u.png)

**Comment by PotcFdk** [comment]
@LUModder Next time, please read the bug report correctly.

**Comment by Tenrys** [comment]
Fixed.
