### ISSUE TITLE
msreporter - add markdown buttons

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#95]
`Originally: msreporter - gsub image links to have ![](url)`
~~Make it so images embed into the issues instead of links~~
Add buttons to the submitter gui for markdown

**Comment by Tenrys** [comment]
Can't you use markdown in-game?

**Comment by danielga** [comment]
How would you know a link is to an image? I can tell you right now imgur doesn't care about extensions. List of image hosts? Still doesn't sound very helpful. Mime types? Requires a GET from the server for each request. I don't see this being automated. Markdown _should_ be supported on the ingame submitter (but I might be talking out of my ass). Can't expect people to know Markdown though.

**Comment by Cynosphere** [comment]
Do what chathud image URL does for links

**Comment by Tenrys** [comment]
Which is?

**Comment by Cynosphere** [comment]
AFAIK its extension based except for some sites like steam images

**Comment by PotcFdk** [comment]
@danielga Markdown does work in the issue submitter.
@Tenrys It's basically a whitelist.

**Comment by Cynosphere** [comment]
Maybe we should just add markdown buttons to the UI instead that do that action

**Comment by Tenrys** [comment]
Great idea.

**Comment by cdr1996** [comment]
Reopen if needed, issue is stale and not receiving attention.
