### ISSUE TITLE
Export old to-do list content here?

### ISSUE THREAD

**Issue by Tenrys** [Metastruct/issues#96]
Should we move some of the most important issues / to-do items from [the old to-do list we had that nobody used](http://metastruct.org/todo/) here?

**Comment by PotcFdk** [comment]
@Python1320 is that page still in use?

**Comment by Cynosphere** [comment]
The page still works, you just have to log into SSO first, but yeah, it's a good idea to port everything over.

**Comment by Tenrys** [comment]
I know it does, it's just because nobody uses it and it has more visibility and is more relevant here.

**Comment by Cynosphere** [comment]
I've started to move stuff over
